from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [("catalog", "0002_catalog_crud_expansion"), ("sales", "0003_salesorder_return_credit_amount")]
    operations = [
        migrations.CreateModel(name="Campaign", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("code", models.CharField(max_length=64, unique=True)), ("name", models.CharField(max_length=180)), ("source", models.CharField(blank=True, max_length=80)), ("medium", models.CharField(blank=True, max_length=80)), ("starts_at", models.DateTimeField()), ("ends_at", models.DateTimeField()), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True))], options={"ordering": ("-starts_at", "-id")}),
        migrations.CreateModel(name="FlashSale", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=180)), ("discount_type", models.CharField(choices=[("fixed", "Fixed amount"), ("percentage", "Percentage")], max_length=20)), ("value", models.DecimalField(decimal_places=2, max_digits=18)), ("starts_at", models.DateTimeField()), ("ends_at", models.DateTimeField()), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("products", models.ManyToManyField(related_name="flash_sales", to="catalog.product"))], options={"ordering": ("-starts_at", "-id")}),
        migrations.CreateModel(name="Coupon", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("code", models.CharField(max_length=40, unique=True)), ("name", models.CharField(max_length=180)), ("discount_type", models.CharField(choices=[("fixed", "Fixed amount"), ("percentage", "Percentage")], max_length=20)), ("value", models.DecimalField(decimal_places=2, max_digits=18)), ("minimum_order_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18)), ("starts_at", models.DateTimeField()), ("ends_at", models.DateTimeField()), ("usage_limit", models.PositiveIntegerField(blank=True, null=True)), ("usage_count", models.PositiveIntegerField(default=0)), ("scope", models.CharField(choices=[("all", "All products"), ("products", "Specific products"), ("categories", "Specific categories")], default="all", max_length=20)), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("campaign", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="coupons", to="promotions.campaign")), ("categories", models.ManyToManyField(blank=True, related_name="marketing_coupons", to="catalog.category")), ("products", models.ManyToManyField(blank=True, related_name="marketing_coupons", to="catalog.product"))], options={"ordering": ("-created_at", "code")}),
        migrations.CreateModel(name="CouponRedemption", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("discount_amount", models.DecimalField(decimal_places=2, max_digits=18)), ("created_at", models.DateTimeField(auto_now_add=True)), ("coupon", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="redemptions", to="promotions.coupon")), ("order", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="coupon_redemption", to="sales.salesorder"))], options={"ordering": ("-created_at", "-id")}),
        migrations.CreateModel(name="CampaignEvent", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("event_type", models.CharField(choices=[("visit", "Visit"), ("coupon_applied", "Coupon Applied"), ("conversion", "Conversion")], max_length=30)), ("tracking_token", models.CharField(blank=True, max_length=64)), ("source", models.CharField(blank=True, max_length=80)), ("medium", models.CharField(blank=True, max_length=80)), ("landing_path", models.CharField(blank=True, max_length=500)), ("referrer", models.CharField(blank=True, max_length=500)), ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18)), ("created_at", models.DateTimeField(auto_now_add=True)), ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="promotions.campaign")), ("coupon", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="campaign_events", to="promotions.coupon")), ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="campaign_events", to="sales.salesorder"))], options={"ordering": ("-created_at", "-id")}),
        migrations.AddIndex(model_name="campaign", index=models.Index(fields=["is_active", "starts_at", "ends_at"], name="promo_campaign_live_idx")),
        migrations.AddIndex(model_name="flashsale", index=models.Index(fields=["is_active", "starts_at", "ends_at"], name="promo_flash_live_idx")),
        migrations.AddIndex(model_name="coupon", index=models.Index(fields=["is_active", "starts_at", "ends_at"], name="promo_coupon_live_idx")),
        migrations.AddIndex(model_name="coupon", index=models.Index(fields=["campaign", "is_active"], name="promo_coupon_campaign_idx")),
        migrations.AddIndex(model_name="campaignevent", index=models.Index(fields=["campaign", "event_type", "created_at"], name="promo_event_campaign_idx")),
        migrations.AddIndex(model_name="campaignevent", index=models.Index(fields=["tracking_token", "created_at"], name="promo_event_token_idx")),
        migrations.AddConstraint(model_name="campaignevent", constraint=models.UniqueConstraint(fields=("campaign", "order", "event_type"), name="uniq_promo_campaign_order_event")),
    ]
