"""Static catalog. Keep IDs stable because browser carts store these IDs."""

PRODUCTS = [{'id': 'baseus',
  'name': 'Baseus Bowie E16 TWS Earbuds',
  'price': 2490,
  'rating': '4.6 (320)',
  'badge': 'Bestseller',
  'category': 'TWS Earbuds',
  'brand': 'Baseus',
  'stock': 32,
  'variant': 'White',
  'slug': 'baseus-bowie-e16-tws-earbuds',
  'image': 'store/images/baseus-e16.webp',
  'regular_price': 3200,
  'badge_class': 'green',
  'images': ['store/images/baseus-thumb-1.webp',
             'store/images/baseus-thumb-2.webp',
             'store/images/baseus-thumb-3.webp',
             'store/images/baseus-thumb-4.webp',
             'store/images/baseus-thumb-5.webp'],
  'detail_image': 'store/images/baseus-detail.webp',
  'short_name': 'Baseus Bowie E16',
  'subtitle': 'Immersive Sound, All Day Comfort',
  'description': 'Experience powerful sound and all-day comfort with Baseus Bowie E16. With '
                 "Bluetooth 5.3, long battery life and crystal clear calls, it's your perfect "
                 'everyday audio companion.',
  'description_paragraphs': ['The Baseus Bowie E16 TWS Earbuds deliver an exceptional audio '
                             'experience with rich, balanced sound, deep bass and clear vocals. '
                             'Designed for your everyday lifestyle, these earbuds offer a '
                             'comfortable fit, long battery life and reliable Bluetooth 5.3 '
                             'connectivity.',
                             "Whether you're listening to music, taking calls or gaming, the Bowie "
                             'E16 ensures crystal clear audio and low latency.'],
  'features': ['🔊 Rich, balanced sound',
               '⌁ Bluetooth 5.3 stable connection',
               '🎙 AI noise reduction for clear calls',
               '☝ Touch control',
               '◉ Up to 30 hours total playtime',
               '💧 IPX4 water resistance',
               '◎ Comfortable and lightweight design',
               '▣ Wide device compatibility'],
  'specifications': [{'name': 'Brand', 'value': 'Baseus'},
                     {'name': 'Model', 'value': 'Bowie E16'},
                     {'name': 'Bluetooth Version', 'value': '5.3'},
                     {'name': 'Playtime', 'value': 'Up to 6 hours / 30 hours with case'},
                     {'name': 'Charging Port', 'value': 'USB Type-C'},
                     {'name': 'Water Resistance', 'value': 'IPX4'},
                     {'name': 'Microphone', 'value': 'AI Noise Reduction'},
                     {'name': 'Touch Control', 'value': 'Yes'},
                     {'name': 'Compatibility', 'value': 'Android, iOS, Windows, macOS'}],
  'variants': [{'name': 'White', 'symbol': '⚪'},
               {'name': 'Black', 'symbol': '⚫'},
               {'name': 'Pink', 'symbol': '🩷'},
               {'name': 'Blue', 'symbol': '🔵'}],
  'box_contents': ['2 × Baseus Bowie E16 Earbuds (L &amp; R)',
                   '1 × Charging Case',
                   '1 × USB Type-C Charging Cable',
                   '1 × User Manual'],
  'review_score': '4.6',
  'review_count': '320',
  'detail_badge': '20% OFF',
  'detail_regular_price': 3290},
 {'id': 'q20i',
  'name': 'Anker Soundcore Q20i Wireless Headphones',
  'price': 7990,
  'rating': '4.7 (184)',
  'badge': '20% OFF',
  'category': 'Headphones',
  'brand': 'Anker',
  'stock': 18,
  'variant': 'Black',
  'slug': 'anker-soundcore-q20i-wireless-headphones',
  'image': 'store/images/q20i.webp',
  'regular_price': 8990,
  'badge_class': 'red',
  'images': ['store/images/q20i.webp'],
  'detail_image': 'store/images/q20i.webp',
  'short_name': 'Anker Soundcore Q20i Wireless Headphones',
  'subtitle': 'Authentic Anker electronics and accessories',
  'description': 'Anker Soundcore Q20i Wireless Headphones from TechBari. See the specifications '
                 'and available variant below.',
  'description_paragraphs': ['Anker Soundcore Q20i Wireless Headphones from TechBari. See the '
                             'specifications and available variant below.'],
  'features': ['Headphones', 'Anker original product'],
  'specifications': [{'name': 'Brand', 'value': 'Anker'},
                     {'name': 'Category', 'value': 'Headphones'},
                     {'name': 'Color', 'value': 'Black'}],
  'variants': [{'name': 'Black', 'symbol': '⚫'}],
  'box_contents': ['Anker Soundcore Q20i Wireless Headphones'],
  'review_score': '4.7',
  'review_count': '184',
  'detail_badge': '20% OFF'},
 {'id': 'haylou',
  'name': 'Haylou RS4 Plus Smartwatch',
  'price': 4990,
  'rating': '4.5 (96)',
  'badge': 'New',
  'category': 'Smartwatches',
  'brand': 'Haylou',
  'stock': 24,
  'variant': 'Black',
  'slug': 'haylou-rs4-plus-smartwatch',
  'image': 'store/images/haylou-rs4.webp',
  'regular_price': 5990,
  'badge_class': 'blue',
  'images': ['store/images/haylou-rs4.webp'],
  'detail_image': 'store/images/haylou-rs4.webp',
  'short_name': 'Haylou RS4 Plus Smartwatch',
  'subtitle': 'Authentic Haylou electronics and accessories',
  'description': 'Haylou RS4 Plus Smartwatch from TechBari. See the specifications and available '
                 'variant below.',
  'description_paragraphs': ['Haylou RS4 Plus Smartwatch from TechBari. See the specifications and '
                             'available variant below.'],
  'features': ['Smartwatches', 'Haylou original product'],
  'specifications': [{'name': 'Brand', 'value': 'Haylou'},
                     {'name': 'Category', 'value': 'Smartwatches'},
                     {'name': 'Color', 'value': 'Black'}],
  'variants': [{'name': 'Black', 'symbol': '⚫'}],
  'box_contents': ['Haylou RS4 Plus Smartwatch'],
  'review_score': '4.5',
  'review_count': '96',
  'detail_badge': 'New'},
 {'id': 'jbl',
  'name': 'JBL Flip 6 Bluetooth Speaker',
  'price': 8990,
  'rating': '4.8 (231)',
  'badge': 'Hot',
  'category': 'Speakers',
  'brand': 'JBL',
  'stock': 16,
  'variant': 'Black',
  'slug': 'jbl-flip-6-bluetooth-speaker',
  'image': 'store/images/jbl-flip6.webp',
  'regular_price': 9990,
  'badge_class': 'red',
  'images': ['store/images/jbl-flip6.webp'],
  'detail_image': 'store/images/jbl-flip6.webp',
  'short_name': 'JBL Flip 6 Bluetooth Speaker',
  'subtitle': 'Authentic JBL electronics and accessories',
  'description': 'JBL Flip 6 Bluetooth Speaker from TechBari. See the specifications and available '
                 'variant below.',
  'description_paragraphs': ['JBL Flip 6 Bluetooth Speaker from TechBari. See the specifications '
                             'and available variant below.'],
  'features': ['Speakers', 'JBL original product'],
  'specifications': [{'name': 'Brand', 'value': 'JBL'},
                     {'name': 'Category', 'value': 'Speakers'},
                     {'name': 'Color', 'value': 'Black'}],
  'variants': [{'name': 'Black', 'symbol': '⚫'}],
  'box_contents': ['JBL Flip 6 Bluetooth Speaker'],
  'review_score': '4.8',
  'review_count': '231',
  'detail_badge': 'Hot'},
 {'id': 'xiaomi',
  'name': 'Xiaomi 20000mAh Power Bank (22.5W)',
  'price': 2190,
  'rating': '4.6 (231)',
  'badge': 'Bestseller',
  'category': 'Power Banks',
  'brand': 'Xiaomi',
  'stock': 20,
  'variant': 'Black',
  'slug': 'xiaomi-20000mah-power-bank-22-5w',
  'image': 'store/images/xiaomi-powerbank.webp',
  'regular_price': 2590,
  'badge_class': 'green',
  'images': ['store/images/xiaomi-powerbank.webp'],
  'detail_image': 'store/images/xiaomi-powerbank.webp',
  'short_name': 'Xiaomi 20000mAh Power Bank (22.5W)',
  'subtitle': 'Authentic Xiaomi electronics and accessories',
  'description': 'Xiaomi 20000mAh Power Bank (22.5W) from TechBari. See the specifications and '
                 'available variant below.',
  'description_paragraphs': ['Xiaomi 20000mAh Power Bank (22.5W) from TechBari. See the '
                             'specifications and available variant below.'],
  'features': ['Power Banks', 'Xiaomi original product'],
  'specifications': [{'name': 'Brand', 'value': 'Xiaomi'},
                     {'name': 'Category', 'value': 'Power Banks'},
                     {'name': 'Color', 'value': 'Black'}],
  'variants': [{'name': 'Black', 'symbol': '⚫'}],
  'box_contents': ['Xiaomi 20000mAh Power Bank (22.5W)'],
  'review_score': '4.6',
  'review_count': '231',
  'detail_badge': 'Bestseller'},
 {'id': 'anker',
  'name': 'Anker 30W USB-C Wall Charger',
  'price': 1490,
  'rating': '4.8 (178)',
  'badge': 'Bestseller',
  'category': 'Chargers',
  'brand': 'Anker',
  'stock': 34,
  'variant': 'White',
  'slug': 'anker-30w-usb-c-wall-charger',
  'image': 'store/images/anker-charger.webp',
  'regular_price': 1890,
  'badge_class': 'green',
  'images': ['store/images/anker-charger.webp'],
  'detail_image': 'store/images/anker-charger.webp',
  'short_name': 'Anker 30W USB-C Wall Charger',
  'subtitle': 'Authentic Anker electronics and accessories',
  'description': 'Anker 30W USB-C Wall Charger from TechBari. See the specifications and available '
                 'variant below.',
  'description_paragraphs': ['Anker 30W USB-C Wall Charger from TechBari. See the specifications '
                             'and available variant below.'],
  'features': ['Chargers', 'Anker original product'],
  'specifications': [{'name': 'Brand', 'value': 'Anker'},
                     {'name': 'Category', 'value': 'Chargers'},
                     {'name': 'Color', 'value': 'White'}],
  'variants': [{'name': 'White', 'symbol': '⚪'}],
  'box_contents': ['Anker 30W USB-C Wall Charger'],
  'review_score': '4.8',
  'review_count': '178',
  'detail_badge': 'Bestseller'},
 {'id': 'ugreen',
  'name': 'UGREEN USB-C to USB-C Cable (100W)',
  'price': 690,
  'rating': '4.7 (112)',
  'badge': 'New',
  'category': 'Cables',
  'brand': 'UGREEN',
  'stock': 55,
  'variant': 'Black',
  'slug': 'ugreen-usb-c-to-usb-c-cable-100w',
  'image': 'store/images/ugreen-cable.webp',
  'regular_price': 990,
  'badge_class': 'red',
  'images': ['store/images/ugreen-cable.webp'],
  'detail_image': 'store/images/ugreen-cable.webp',
  'short_name': 'UGREEN USB-C to USB-C Cable (100W)',
  'subtitle': 'Authentic UGREEN electronics and accessories',
  'description': 'UGREEN USB-C to USB-C Cable (100W) from TechBari. See the specifications and '
                 'available variant below.',
  'description_paragraphs': ['UGREEN USB-C to USB-C Cable (100W) from TechBari. See the '
                             'specifications and available variant below.'],
  'features': ['Cables', 'UGREEN original product'],
  'specifications': [{'name': 'Brand', 'value': 'UGREEN'},
                     {'name': 'Category', 'value': 'Cables'},
                     {'name': 'Color', 'value': 'Black'}],
  'variants': [{'name': 'Black', 'symbol': '⚫'}],
  'box_contents': ['UGREEN USB-C to USB-C Cable (100W)'],
  'review_score': '4.7',
  'review_count': '112',
  'detail_badge': 'New'},
 {'id': 'budsfe',
  'name': 'Samsung Galaxy Buds FE TWS Earbuds',
  'price': 8990,
  'rating': '4.5 (203)',
  'badge': 'New',
  'category': 'TWS Earbuds',
  'brand': 'Samsung',
  'stock': 14,
  'variant': 'White',
  'slug': 'samsung-galaxy-buds-fe-tws-earbuds',
  'image': 'store/images/galaxy-buds.webp',
  'regular_price': 9490,
  'badge_class': 'blue',
  'images': ['store/images/galaxy-buds.webp'],
  'detail_image': 'store/images/galaxy-buds.webp',
  'short_name': 'Samsung Galaxy Buds FE TWS Earbuds',
  'subtitle': 'Authentic Samsung electronics and accessories',
  'description': 'Samsung Galaxy Buds FE TWS Earbuds from TechBari. See the specifications and '
                 'available variant below.',
  'description_paragraphs': ['Samsung Galaxy Buds FE TWS Earbuds from TechBari. See the '
                             'specifications and available variant below.'],
  'features': ['TWS Earbuds', 'Samsung original product'],
  'specifications': [{'name': 'Brand', 'value': 'Samsung'},
                     {'name': 'Category', 'value': 'TWS Earbuds'},
                     {'name': 'Color', 'value': 'White'}],
  'variants': [{'name': 'White', 'symbol': '⚪'}],
  'box_contents': ['Samsung Galaxy Buds FE TWS Earbuds'],
  'review_score': '4.5',
  'review_count': '203',
  'detail_badge': 'New'},
 {'id': 'neckband',
  'name': 'realme Buds Wireless 3 Neckband Earphones',
  'price': 2590,
  'rating': '4.4 (98)',
  'badge': '21% OFF',
  'category': 'Neckband',
  'brand': 'realme',
  'stock': 21,
  'variant': 'Black',
  'slug': 'realme-buds-wireless-3-neckband-earphones',
  'image': 'store/images/realme-neckband.webp',
  'regular_price': 3290,
  'badge_class': 'red',
  'images': ['store/images/realme-neckband.webp'],
  'detail_image': 'store/images/realme-neckband.webp',
  'short_name': 'realme Buds Wireless 3 Neckband Earphones',
  'subtitle': 'Authentic realme electronics and accessories',
  'description': 'realme Buds Wireless 3 Neckband Earphones from TechBari. See the specifications '
                 'and available variant below.',
  'description_paragraphs': ['realme Buds Wireless 3 Neckband Earphones from TechBari. See the '
                             'specifications and available variant below.'],
  'features': ['Neckband', 'realme original product'],
  'specifications': [{'name': 'Brand', 'value': 'realme'},
                     {'name': 'Category', 'value': 'Neckband'},
                     {'name': 'Color', 'value': 'Black'}],
  'variants': [{'name': 'Black', 'symbol': '⚫'}],
  'box_contents': ['realme Buds Wireless 3 Neckband Earphones'],
  'review_score': '4.4',
  'review_count': '98',
  'detail_badge': '21% OFF'},
 {'id': 'amazfit',
  'name': 'Amazfit Bip 5 Smartwatch',
  'price': 5490,
  'rating': '4.4 (76)',
  'badge': 'Bestseller',
  'category': 'Smartwatches',
  'brand': 'Amazfit',
  'stock': 12,
  'variant': 'Black',
  'slug': 'amazfit-bip-5-smartwatch',
  'image': 'store/images/amazfit-bip5.webp',
  'regular_price': 5990,
  'badge_class': 'green',
  'images': ['store/images/amazfit-bip5.webp'],
  'detail_image': 'store/images/amazfit-bip5.webp',
  'short_name': 'Amazfit Bip 5 Smartwatch',
  'subtitle': 'Authentic Amazfit electronics and accessories',
  'description': 'Amazfit Bip 5 Smartwatch from TechBari. See the specifications and available '
                 'variant below.',
  'description_paragraphs': ['Amazfit Bip 5 Smartwatch from TechBari. See the specifications and '
                             'available variant below.'],
  'features': ['Smartwatches', 'Amazfit original product'],
  'specifications': [{'name': 'Brand', 'value': 'Amazfit'},
                     {'name': 'Category', 'value': 'Smartwatches'},
                     {'name': 'Color', 'value': 'Black'}],
  'variants': [{'name': 'Black', 'symbol': '⚫'}],
  'box_contents': ['Amazfit Bip 5 Smartwatch'],
  'review_score': '4.4',
  'review_count': '76',
  'detail_badge': 'Bestseller'},
 {'id': 'boat',
  'name': 'boAt Stone 620 Bluetooth Speaker',
  'price': 3190,
  'rating': '4.3 (189)',
  'badge': 'Hot',
  'category': 'Speakers',
  'brand': 'boAt',
  'stock': 29,
  'variant': 'Blue',
  'slug': 'boat-stone-620-bluetooth-speaker',
  'image': 'store/images/boat-speaker.webp',
  'regular_price': 3490,
  'badge_class': 'red',
  'images': ['store/images/boat-speaker.webp'],
  'detail_image': 'store/images/boat-speaker.webp',
  'short_name': 'boAt Stone 620 Bluetooth Speaker',
  'subtitle': 'Authentic boAt electronics and accessories',
  'description': 'boAt Stone 620 Bluetooth Speaker from TechBari. See the specifications and '
                 'available variant below.',
  'description_paragraphs': ['boAt Stone 620 Bluetooth Speaker from TechBari. See the '
                             'specifications and available variant below.'],
  'features': ['Speakers', 'boAt original product'],
  'specifications': [{'name': 'Brand', 'value': 'boAt'},
                     {'name': 'Category', 'value': 'Speakers'},
                     {'name': 'Color', 'value': 'Blue'}],
  'variants': [{'name': 'Blue', 'symbol': '⚪'}],
  'box_contents': ['boAt Stone 620 Bluetooth Speaker'],
  'review_score': '4.3',
  'review_count': '189',
  'detail_badge': 'Hot'},
 {'id': 'airpods',
  'name': 'Apple AirPods Pro 2 TWS Earbuds',
  'price': 28990,
  'rating': '4.7 (341)',
  'badge': 'Bestseller',
  'category': 'TWS Earbuds',
  'brand': 'Apple',
  'stock': 9,
  'variant': 'White',
  'slug': 'apple-airpods-pro-2-tws-earbuds',
  'image': 'store/images/airpods-pro2.webp',
  'regular_price': 29990,
  'badge_class': 'green',
  'images': ['store/images/airpods-pro2.webp'],
  'detail_image': 'store/images/airpods-pro2.webp',
  'short_name': 'Apple AirPods Pro 2 TWS Earbuds',
  'subtitle': 'Authentic Apple electronics and accessories',
  'description': 'Apple AirPods Pro 2 TWS Earbuds from TechBari. See the specifications and '
                 'available variant below.',
  'description_paragraphs': ['Apple AirPods Pro 2 TWS Earbuds from TechBari. See the '
                             'specifications and available variant below.'],
  'features': ['TWS Earbuds', 'Apple original product'],
  'specifications': [{'name': 'Brand', 'value': 'Apple'},
                     {'name': 'Category', 'value': 'TWS Earbuds'},
                     {'name': 'Color', 'value': 'White'}],
  'variants': [{'name': 'White', 'symbol': '⚪'}],
  'box_contents': ['Apple AirPods Pro 2 TWS Earbuds'],
  'review_score': '4.7',
  'review_count': '341',
  'detail_badge': 'Bestseller'},
 {'id': 'baseuspb',
  'name': 'Baseus 10000mAh Power Bank (20W)',
  'price': 1890,
  'rating': '4.4 (117)',
  'badge': 'New',
  'category': 'Power Banks',
  'brand': 'Baseus',
  'stock': 26,
  'variant': 'Black',
  'slug': 'baseus-10000mah-power-bank-20w',
  'image': 'store/images/baseus-powerbank.webp',
  'regular_price': 2190,
  'badge_class': 'blue',
  'images': ['store/images/baseus-powerbank.webp'],
  'detail_image': 'store/images/baseus-powerbank.webp',
  'short_name': 'Baseus 10000mAh Power Bank (20W)',
  'subtitle': 'Authentic Baseus electronics and accessories',
  'description': 'Baseus 10000mAh Power Bank (20W) from TechBari. See the specifications and '
                 'available variant below.',
  'description_paragraphs': ['Baseus 10000mAh Power Bank (20W) from TechBari. See the '
                             'specifications and available variant below.'],
  'features': ['Power Banks', 'Baseus original product'],
  'specifications': [{'name': 'Brand', 'value': 'Baseus'},
                     {'name': 'Category', 'value': 'Power Banks'},
                     {'name': 'Color', 'value': 'Black'}],
  'variants': [{'name': 'Black', 'symbol': '⚫'}],
  'box_contents': ['Baseus 10000mAh Power Bank (20W)'],
  'review_score': '4.4',
  'review_count': '117',
  'detail_badge': 'New'},
 {'id': 'samsungc',
  'name': 'Samsung 25W USB-C Wall Charger',
  'price': 1290,
  'rating': '4.6 (145)',
  'badge': '15% OFF',
  'category': 'Chargers',
  'brand': 'Samsung',
  'stock': 31,
  'variant': 'White',
  'slug': 'samsung-25w-usb-c-wall-charger',
  'image': 'store/images/samsung-charger.webp',
  'regular_price': 1590,
  'badge_class': 'red',
  'images': ['store/images/samsung-charger.webp'],
  'detail_image': 'store/images/samsung-charger.webp',
  'short_name': 'Samsung 25W USB-C Wall Charger',
  'subtitle': 'Authentic Samsung electronics and accessories',
  'description': 'Samsung 25W USB-C Wall Charger from TechBari. See the specifications and '
                 'available variant below.',
  'description_paragraphs': ['Samsung 25W USB-C Wall Charger from TechBari. See the specifications '
                             'and available variant below.'],
  'features': ['Chargers', 'Samsung original product'],
  'specifications': [{'name': 'Brand', 'value': 'Samsung'},
                     {'name': 'Category', 'value': 'Chargers'},
                     {'name': 'Color', 'value': 'White'}],
  'variants': [{'name': 'White', 'symbol': '⚪'}],
  'box_contents': ['Samsung 25W USB-C Wall Charger'],
  'review_score': '4.6',
  'review_count': '145',
  'detail_badge': '15% OFF'},
 {'id': 'sony',
  'name': 'Sony WH-CH520 Wireless Headphones',
  'price': 8490,
  'rating': '4.5 (132)',
  'badge': 'New',
  'category': 'Headphones',
  'brand': 'Sony',
  'stock': 17,
  'variant': 'Black',
  'slug': 'sony-wh-ch520-wireless-headphones',
  'image': 'store/images/sony-whch520.webp',
  'regular_price': 8990,
  'badge_class': 'blue',
  'images': ['store/images/sony-whch520.webp'],
  'detail_image': 'store/images/sony-whch520.webp',
  'short_name': 'Sony WH-CH520 Wireless Headphones',
  'subtitle': 'Authentic Sony electronics and accessories',
  'description': 'Sony WH-CH520 Wireless Headphones from TechBari. See the specifications and '
                 'available variant below.',
  'description_paragraphs': ['Sony WH-CH520 Wireless Headphones from TechBari. See the '
                             'specifications and available variant below.'],
  'features': ['Headphones', 'Sony original product'],
  'specifications': [{'name': 'Brand', 'value': 'Sony'},
                     {'name': 'Category', 'value': 'Headphones'},
                     {'name': 'Color', 'value': 'Black'}],
  'variants': [{'name': 'Black', 'symbol': '⚫'}],
  'box_contents': ['Sony WH-CH520 Wireless Headphones'],
  'review_score': '4.5',
  'review_count': '132',
  'detail_badge': 'New'}]

CATEGORIES = [{'name': 'TWS Earbuds', 'image': 'store/images/cat-earbuds.webp', 'count': 58},
 {'name': 'Over-Ear Headphones', 'image': 'store/images/cat-headphones.webp', 'count': 42},
 {'name': 'Neckband Earphones', 'image': 'store/images/cat-neckband.webp', 'count': 28},
 {'name': 'Smartwatches', 'image': 'store/images/cat-watch.webp', 'count': 46},
 {'name': 'Bluetooth Speakers', 'image': 'store/images/cat-speaker.webp', 'count': 32},
 {'name': 'Power Banks', 'image': 'store/images/cat-powerbank.webp', 'count': 38},
 {'name': 'Wall Chargers', 'image': 'store/images/cat-charger.webp', 'count': 44},
 {'name': 'Cables', 'image': 'store/images/cat-cable.webp', 'count': 36},
 {'name': 'Phone Accessories', 'image': 'store/images/cat-stand.webp', 'count': 44}]

BRANDS = [{'name': 'Apple', 'count': 28},
 {'name': 'Samsung', 'count': 36},
 {'name': 'Xiaomi', 'count': 42},
 {'name': 'Anker', 'count': 38},
 {'name': 'Baseus', 'count': 32},
 {'name': 'JBL', 'count': 24},
 {'name': 'UGREEN', 'count': 22}]

DEFAULT_CART = [{'id': 'baseus', 'qty': 1, 'variant': 'White'},
 {'id': 'q20i', 'qty': 1, 'variant': 'Black'},
 {'id': 'xiaomi', 'qty': 1, 'variant': 'Black'}]

DEFAULT_WISHLIST = ['baseus', 'q20i', 'haylou', 'xiaomi', 'anker']

HERO_SLIDES = [{'eyebrow': 'Sound that moves you',
  'title': 'Premium Audio<br>For a Better You',
  'text': 'TWS Earbuds | Headphones | Speakers<br>Discover authentic sound. Only at TechBari.',
  'cta': 'Shop Audio Products →',
  'alt': 'Premium audio products',
  'image': 'store/images/hero-audio.webp'},
 {'eyebrow': 'Power your day',
  'title': 'Reliable Power<br>Always With You',
  'text': 'Power Banks | Chargers | Cables<br>Fast, dependable charging for every device.',
  'cta': 'Shop Power Solutions →',
  'alt': 'Power banks chargers and cables',
  'image': 'store/images/promo-power.webp'},
 {'eyebrow': 'Style meets function',
  'title': 'Smartwatches<br>For a Smarter You',
  'text': 'Track. Stay Connected. Do More.<br>Smart wearables for everyday life.',
  'cta': 'Shop Smartwatches →',
  'alt': 'Smartwatch collection',
  'image': 'store/images/promo-watch.webp'}]

COUPONS = {'SAVE1000': {'type': 'fixed', 'value': 1000, 'label': 'SAVE1000'},
 'SAVE500': {'type': 'fixed', 'value': 500, 'label': 'SAVE500'},
 'TECH10': {'type': 'percent', 'value': 10, 'label': 'TECH10'}}


PRODUCTS[0]["reviews"] = [{'author': 'Tanvir H.', 'text': 'Amazing sound quality and battery life. Great value for money!'},
 {'author': 'Nusrat J.', 'text': 'Very comfortable and the call quality is superb.'}]
PRODUCTS[0]["questions"] = [{'answer': 'Yes. Bowie E16 works with Android, iOS, Windows and macOS devices that support '
            'Bluetooth.',
  'question': 'Q: Does it support Android and iPhone?'},
 {'answer': 'Yes, Cash on Delivery is available across supported delivery areas in Bangladesh.',
  'question': 'Q: Is Cash on Delivery available?'},
 {'answer': 'Warranty eligibility is shown on the product and invoice. Keep your invoice for '
            'warranty service.',
  'question': 'Q: Does it include an official warranty?'}]
for product in PRODUCTS[1:]:
    product["reviews"] = []
    product["questions"] = PRODUCTS[0]["questions"][1:]

TRACKING_ORDER = {'courier': 'Pathao Courier',
 'customer': 'Tanvir Hossain',
 'discount': 500,
 'order_no': 'TB123456',
 'placed_at': '12 Mar 2026, 10:24 AM',
 'product_name': 'Anker Soundcore Q20i Wireless Headphones',
 'subtotal': 7990,
 'total': 7490,
 'tracking_no': 'PTH123456789BD'}
