"""Static business fixtures. Browser edits remain local to the current browser."""

SEEDS = {'products': [{'id': 1,
               'name': 'AirPods Pro 2 (USB-C)',
               'sku': 'TB-AP2-001',
               'category': 'Earbuds',
               'brand': 'Apple',
               'price': 32999,
               'stock': 45,
               'status': 'Active',
               'image': 'admin/images/airpods-pro2.webp'},
              {'id': 2,
               'name': 'Sony WH-1000XM5',
               'sku': 'TB-SNY-002',
               'category': 'Headphones',
               'brand': 'Sony',
               'price': 42000,
               'stock': 28,
               'status': 'Active',
               'image': 'admin/images/q20i.webp'},
              {'id': 3,
               'name': 'JBL Flip 6',
               'sku': 'TB-JBL-003',
               'category': 'Speakers',
               'brand': 'JBL',
               'price': 18500,
               'stock': 12,
               'status': 'Active',
               'image': 'admin/images/jbl-flip6.webp'},
              {'id': 4,
               'name': 'Samsung Galaxy Watch 6',
               'sku': 'TB-SAM-004',
               'category': 'Smartwatches',
               'brand': 'Samsung',
               'price': 36999,
               'stock': 8,
               'status': 'Active',
               'image': 'admin/images/haylou-rs4.webp'},
              {'id': 5,
               'name': 'Anker PowerCore 20000',
               'sku': 'TB-ANK-005',
               'category': 'Power Banks',
               'brand': 'Anker',
               'price': 4999,
               'stock': 22,
               'status': 'Active',
               'image': 'admin/images/baseus-powerbank.webp'},
              {'id': 6,
               'name': 'UGREEN 65W GaN Charger',
               'sku': 'TB-UGR-006',
               'category': 'Chargers',
               'brand': 'UGREEN',
               'price': 3999,
               'stock': 50,
               'status': 'Active',
               'image': 'admin/images/anker-charger.webp'},
              {'id': 7,
               'name': 'Baseus USB-C to USB-C',
               'sku': 'TB-BAS-007',
               'category': 'Cables',
               'brand': 'Baseus',
               'price': 1299,
               'stock': 100,
               'status': 'Active',
               'image': 'admin/images/ugreen-cable.webp'},
              {'id': 8,
               'name': 'Redmi Buds 5 Pro',
               'sku': 'TB-RDM-008',
               'category': 'Earbuds',
               'brand': 'Xiaomi',
               'price': 6999,
               'stock': 0,
               'status': 'Out of Stock',
               'image': 'admin/images/galaxy-buds.webp'},
              {'id': 9,
               'name': 'Boat Stone 350',
               'sku': 'TB-BOA-009',
               'category': 'Speakers',
               'brand': 'boAt',
               'price': 4499,
               'stock': 15,
               'status': 'Active',
               'image': 'admin/images/jbl-flip6.webp'},
              {'id': 10,
               'name': 'Amazfit Bip 5',
               'sku': 'TB-AMZ-010',
               'category': 'Smartwatches',
               'brand': 'Amazfit',
               'price': 9999,
               'stock': 6,
               'status': 'Active',
               'image': 'admin/images/haylou-rs4.webp'}],
 'orders': [{'id': 1,
             'orderId': '#TB7842',
             'customer': 'Tanvir Hasan',
             'items': 'iPhone 15 (128GB)',
             'amount': 115000,
             'payment': 'bKash',
             'status': 'Delivered',
             'date': '2025-05-23',
             'order_no': '#TB7842'},
            {'id': 2,
             'orderId': '#TB7841',
             'customer': 'Sadia Islam',
             'items': 'Sony WH-1000XM5',
             'amount': 42000,
             'payment': 'Nagad',
             'status': 'Processing',
             'date': '2025-05-23',
             'order_no': '#TB7841'},
            {'id': 3,
             'orderId': '#TB7840',
             'customer': 'Rafiq Ahmed',
             'items': 'HP Laptop 15s',
             'amount': 78500,
             'payment': 'Card',
             'status': 'Shipped',
             'date': '2025-05-22',
             'order_no': '#TB7840'},
            {'id': 4,
             'orderId': '#TB7839',
             'customer': 'Nusrat Jahan',
             'items': 'Redmi Note 13 Pro',
             'amount': 32999,
             'payment': 'Cash on Delivery',
             'status': 'Delivered',
             'date': '2025-05-22',
             'order_no': '#TB7839'}],
 'categories': [{'id': 1,
                 'name': 'TWS Earbuds',
                 'slug': 'tws-earbuds',
                 'parent': 'Audio',
                 'products': 58,
                 'status': 'Active'},
                {'id': 2,
                 'name': 'Headphones',
                 'slug': 'headphones',
                 'parent': 'Audio',
                 'products': 42,
                 'status': 'Active'},
                {'id': 3,
                 'name': 'Power Banks',
                 'slug': 'power-banks',
                 'parent': 'Accessories',
                 'products': 38,
                 'status': 'Active'}],
 'brands': [{'id': 1,
             'name': 'Apple',
             'slug': 'apple',
             'products': 28,
             'featured': 'Yes',
             'status': 'Active'},
            {'id': 2,
             'name': 'Samsung',
             'slug': 'samsung',
             'products': 36,
             'featured': 'Yes',
             'status': 'Active'},
            {'id': 3,
             'name': 'Baseus',
             'slug': 'baseus',
             'products': 32,
             'featured': 'Yes',
             'status': 'Active'}],
 'serials': [{'id': 1,
              'serial': 'IMEI-865980001',
              'product': 'Samsung Galaxy S24',
              'warehouse': 'Main Warehouse',
              'status': 'In Stock',
              'warrantyEnd': '2027-05-23'},
             {'id': 2,
              'serial': 'SN-AP2-000889',
              'product': 'AirPods Pro 2',
              'warehouse': 'Dhanmondi Store',
              'status': 'Sold',
              'warrantyEnd': '2026-09-11'}],
 'customers': [{'id': 1,
                'name': 'Tanvir Hasan',
                'phone': '+880 1712-345678',
                'email': 'tanvir@gmail.com',
                'orders': 12,
                'spent': 115000,
                'group': 'VIP',
                'status': 'Active'},
               {'id': 2,
                'name': 'Sadia Islam',
                'phone': '+880 1812-987654',
                'email': 'sadia@gmail.com',
                'orders': 5,
                'spent': 42000,
                'group': 'Regular',
                'status': 'Active'},
               {'id': 3,
                'name': 'Rafiq Ahmed',
                'phone': '+880 1730-112233',
                'email': 'rafiq@gmail.com',
                'orders': 8,
                'spent': 78500,
                'group': 'Regular',
                'status': 'Active'}],
 'purchases': [{'id': 1,
                'po': 'PO2025-0186',
                'supplier': 'Transcom Digital',
                'warehouse': 'Main Warehouse',
                'items': '3 items',
                'total': 325000,
                'payment': 'Paid',
                'receipt': 'Received',
                'date': '2025-05-23',
                'status': 'Active'},
               {'id': 2,
                'po': 'PO2025-0185',
                'supplier': 'Star Tech Ltd.',
                'warehouse': 'Main Warehouse',
                'items': '5 items',
                'total': 580000,
                'payment': 'Partial',
                'receipt': 'Partial',
                'date': '2025-05-22',
                'status': 'Active'}],
 'suppliers': [{'id': 1,
                'name': 'Transcom Digital',
                'phone': '01711-223344',
                'email': 'sales@transcom.com',
                'purchases': 1420000,
                'outstanding': 0,
                'terms': '30 Days',
                'status': 'Active'},
               {'id': 2,
                'name': 'Star Tech Ltd.',
                'phone': '01678-556677',
                'email': 'sales@startech.com',
                'purchases': 980000,
                'outstanding': 125000,
                'terms': '15 Days',
                'status': 'Active'}],
 'inventory': [{'id': 1,
                'product': 'AirPods Pro 2',
                'sku': 'AP2-001',
                'warehouse': 'Main Warehouse',
                'available': 45,
                'reserved': 8,
                'reorder': 20,
                'status': 'In Stock'},
               {'id': 2,
                'product': 'Sony WH-1000XM5',
                'sku': 'SNY-002',
                'warehouse': 'Main Warehouse',
                'available': 8,
                'reserved': 2,
                'reorder': 15,
                'status': 'Low Stock'},
               {'id': 3,
                'product': 'Redmi Buds 5 Pro',
                'sku': 'RDM-008',
                'warehouse': 'Dhanmondi Store',
                'available': 0,
                'reserved': 0,
                'reorder': 10,
                'status': 'Out of Stock'}],
 'warehouses': [{'id': 1,
                 'name': 'Main Warehouse',
                 'code': 'WH-MAIN',
                 'branch': 'Head Office',
                 'units': 820,
                 'value': 1850000,
                 'status': 'Active'},
                {'id': 2,
                 'name': 'Dhanmondi Store',
                 'code': 'WH-DHN',
                 'branch': 'Dhanmondi',
                 'units': 248,
                 'value': 620000,
                 'status': 'Active'}],
 'expenses': [{'id': 1,
               'expenseNo': 'EXP-7842',
               'date': '2025-05-23',
               'category': 'Advertising',
               'description': 'Meta Ads',
               'method': 'Bank',
               'amount': 42000,
               'status': 'Posted'},
              {'id': 2,
               'expenseNo': 'EXP-7841',
               'date': '2025-05-22',
               'category': 'Rent',
               'description': 'Office Rent',
               'method': 'Bank',
               'amount': 18000,
               'status': 'Posted'}],
 'payments': [{'id': 1,
               'transaction': 'FT7842',
               'date': '2025-05-23',
               'type': 'Income',
               'method': 'bKash',
               'reference': 'Order TB7842',
               'amount': 115000,
               'status': 'Success'},
              {'id': 2,
               'transaction': 'FT7841',
               'date': '2025-05-23',
               'type': 'Expense',
               'method': 'Bank',
               'reference': 'Supplier Payment',
               'amount': 42000,
               'status': 'Success'}],
 'coupons': [{'id': 1,
              'code': 'EID10',
              'type': 'Percent',
              'value': 10,
              'minimum': 5000,
              'usage': 1000,
              'expiry': '2025-05-31',
              'status': 'Active'},
             {'id': 2,
              'code': 'TECH20',
              'type': 'Percent',
              'value': 20,
              'minimum': 10000,
              'usage': 500,
              'expiry': '2025-05-28',
              'status': 'Active'}],
 'shipping': [{'id': 1,
               'shipment': 'SHP-7842',
               'order': '#TB7842',
               'customer': 'Tanvir Hasan',
               'courier': 'Steadfast',
               'tracking': 'STD1254687',
               'cod': 115000,
               'status': 'In Transit',
               'date': '2025-05-23'},
              {'id': 2,
               'shipment': 'SHP-7841',
               'order': '#TB7841',
               'customer': 'Sadia Islam',
               'courier': 'Pathao',
               'tracking': 'PH09876543',
               'cod': 42000,
               'status': 'Pending',
               'date': '2025-05-23'}],
 'returns': [{'id': 1,
              'returnId': 'RET7842',
              'orderId': '#TB7842',
              'customer': 'Tanvir Hasan',
              'item': 'iPhone 15',
              'reason': 'Defective item',
              'refund': 115000,
              'status': 'Pending',
              'date': '2025-05-23',
              'order_no': '#TB7842'},
             {'id': 2,
              'returnId': 'RET7841',
              'orderId': '#TB7841',
              'customer': 'Sadia Islam',
              'item': 'Sony WH-1000XM5',
              'reason': 'Changed mind',
              'refund': 42000,
              'status': 'Approved',
              'date': '2025-05-22',
              'order_no': '#TB7841'}],
 'warranty': [{'id': 1,
               'claim': 'WR-1024',
               'customer': 'Tanvir Hasan',
               'product': 'AirPods Pro 2',
               'serial': 'SN-AP2-000889',
               'issue': 'Left earbud not charging',
               'resolution': 'Repair',
               'status': 'Inspection',
               'date': '2025-05-23'}],
 'users': [{'id': 1,
            'name': 'Tanvir Hasan',
            'email': 'tanvir@techbari.com',
            'role': 'Manager',
            'branch': 'Head Office',
            'status': 'Active',
            'lastLogin': 'May 23, 10:24 AM'},
           {'id': 2,
            'name': 'Sadia Islam',
            'email': 'sadia@techbari.com',
            'role': 'Cashier',
            'branch': 'Dhanmondi',
            'status': 'Active',
            'lastLogin': 'May 23, 09:15 AM'}],
 'audit': [{'id': 1,
            'date': 'May 23, 10:24 AM',
            'user': 'Admin',
            'action': 'Price Change',
            'module': 'Products',
            'reference': 'TB-AP2-001',
            'ip': '103.12.88.14',
            'result': 'Success',
            'status': 'Active'},
           {'id': 2,
            'date': 'May 23, 09:15 AM',
            'user': 'Nusrat Jahan',
            'action': 'Expense Posted',
            'module': 'Accounts',
            'reference': 'EXP-7841',
            'ip': '103.12.88.31',
            'result': 'Success',
            'status': 'Active'}]}

POS_PRODUCTS = [{'id': 101,
  'name': 'iPhone 15 (128GB)',
  'category': 'Smartphones',
  'price': 115000,
  'stock': 48,
  'image': 'admin/images/pos-iphone.jpg',
  'sku': 'IP15-128-BLK'},
 {'id': 102,
  'name': 'Samsung Galaxy S24',
  'category': 'Smartphones',
  'price': 89999,
  'stock': 35,
  'image': 'admin/images/pos-samsung-s24.jpg',
  'sku': 'SGS24-256'},
 {'id': 103,
  'name': 'Redmi Note 13 Pro',
  'category': 'Smartphones',
  'price': 32999,
  'stock': 62,
  'image': 'admin/images/pos-redmi.jpg',
  'sku': 'RN13P-128'},
 {'id': 104,
  'name': 'Sony WH-1000XM5',
  'category': 'Audio',
  'price': 42000,
  'stock': 28,
  'image': 'admin/images/pos-sony.jpg',
  'sku': 'SNY-XM5'},
 {'id': 105,
  'name': 'HP Laptop 15s (i5)',
  'category': 'Laptops',
  'price': 78500,
  'stock': 21,
  'image': 'admin/images/pos-hp-laptop.jpg',
  'sku': 'HP15S-I5'},
 {'id': 106,
  'name': 'Lenovo IdeaPad 3',
  'category': 'Laptops',
  'price': 62000,
  'stock': 18,
  'image': 'admin/images/pos-lenovo.jpg',
  'sku': 'LNV-IP3'},
 {'id': 107,
  'name': 'Samsung 24” FHD Monitor',
  'category': 'Monitors',
  'price': 18500,
  'stock': 27,
  'image': 'admin/images/pos-monitor.jpg',
  'sku': 'SM24-FHD'},
 {'id': 108,
  'name': 'Logitech MK345',
  'category': 'Accessories',
  'price': 4200,
  'stock': 56,
  'image': 'admin/images/pos-logitech.jpg',
  'sku': 'LOGI-MK345'},
 {'id': 109,
  'name': 'TP-Link Archer C6',
  'category': 'Network',
  'price': 5500,
  'stock': 33,
  'image': 'admin/images/pos-router.jpg',
  'sku': 'TPL-C6'},
 {'id': 110,
  'name': 'JBL Flip 6',
  'category': 'Audio',
  'price': 14500,
  'stock': 19,
  'image': 'admin/images/pos-jbl.jpg',
  'sku': 'JBL-FLIP6'},
 {'id': 111,
  'name': 'Anker PowerCore 20000',
  'category': 'Accessories',
  'price': 6200,
  'stock': 41,
  'image': 'admin/images/pos-powerbank.jpg',
  'sku': 'ANK-PC20K'},
 {'id': 112,
  'name': 'Xbox Wireless Controller',
  'category': 'Gaming',
  'price': 8900,
  'stock': 25,
  'image': 'admin/images/pos-controller.jpg',
  'sku': 'XBOX-WC'}]

STATISTICS = {'accounts': [{'icon': 'backoffice/components/icons/icon_0.html',
               'color': 'green',
               'label': 'Cash in Hand',
               'value': '৳ 325,420',
               'note': 'vs last month',
               'trend': '↑ 12.5%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_1.html',
               'color': 'blue',
               'label': 'Bank Balance',
               'value': '৳ 1,248,900',
               'note': 'vs last month',
               'trend': '↑ 8.3%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_1.html',
               'color': 'purple',
               'label': 'bKash / Nagad',
               'value': '৳ 284,650',
               'note': 'vs last month',
               'trend': '↑ 15.2%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_2.html',
               'color': 'orange',
               'label': 'Receivable',
               'value': '৳ 482,300',
               'note': 'vs last month',
               'trend': '↑ 6.8%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_1.html',
               'color': 'red',
               'label': 'Payable',
               'value': '৳ 312,750',
               'note': 'vs last month',
               'trend': '↑ 4.1%',
               'trend_class': 'up'}],
 'audit_log': [{'icon': 'backoffice/components/icons/icon_3.html',
                'color': 'blue',
                'label': 'Events Today',
                'value': '248',
                'note': 'vs yesterday',
                'trend': '↑ 11%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_4.html',
                'color': 'red',
                'label': 'High Risk',
                'value': '7',
                'note': 'vs yesterday',
                'trend': '↑ 2',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_5.html',
                'color': 'orange',
                'label': 'Stock Changes',
                'value': '18',
                'note': 'vs yesterday',
                'trend': '↑ 4',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_6.html',
                'color': 'green',
                'label': 'Finance Posts',
                'value': '42',
                'note': 'vs yesterday',
                'trend': '↑ 8',
                'trend_class': 'up'}],
 'brand_add': [],
 'brands': [{'icon': 'backoffice/components/icons/icon_5.html',
             'color': 'blue',
             'label': 'Total Brands',
             'value': '28',
             'note': 'vs last month',
             'trend': '↑ 8.1%',
             'trend_class': 'up'},
            {'icon': 'backoffice/components/icons/icon_7.html',
             'color': 'green',
             'label': 'Featured Brands',
             'value': '9',
             'note': 'vs last month',
             'trend': '↑ 4.0%',
             'trend_class': 'up'},
            {'icon': 'backoffice/components/icons/icon_5.html',
             'color': 'purple',
             'label': 'Active Brands',
             'value': '26',
             'note': 'vs last month',
             'trend': '↑ 6.4%',
             'trend_class': 'up'},
            {'icon': 'backoffice/components/icons/icon_5.html',
             'color': 'orange',
             'label': 'Brand Products',
             'value': '248',
             'note': 'vs last month',
             'trend': '↑ 12.5%',
             'trend_class': 'up'}],
 'categories': [{'icon': 'backoffice/components/icons/icon_5.html',
                 'color': 'blue',
                 'label': 'Total Categories',
                 'value': '12',
                 'note': 'vs last month',
                 'trend': '↑ 20%',
                 'trend_class': 'up'},
                {'icon': 'backoffice/components/icons/icon_7.html',
                 'color': 'green',
                 'label': 'Active Categories',
                 'value': '11',
                 'note': 'vs last month',
                 'trend': '↑ 10%',
                 'trend_class': 'up'},
                {'icon': 'backoffice/components/icons/icon_5.html',
                 'color': 'purple',
                 'label': 'Subcategories',
                 'value': '28',
                 'note': 'vs last month',
                 'trend': '↑ 27.3%',
                 'trend_class': 'up'},
                {'icon': 'backoffice/components/icons/icon_5.html',
                 'color': 'orange',
                 'label': 'Products in Categories',
                 'value': '248',
                 'note': 'vs last month',
                 'trend': '↑ 14.2%',
                 'trend_class': 'up'}],
 'category_add': [],
 'coupon_add': [],
 'coupons': [{'icon': 'backoffice/components/icons/icon_5.html',
              'color': 'green',
              'label': 'Active Coupons',
              'value': '12',
              'note': 'vs last month',
              'trend': '↑ 9.1%',
              'trend_class': 'up'},
             {'icon': 'backoffice/components/icons/icon_3.html',
              'color': 'blue',
              'label': 'Uses',
              'value': '2,468',
              'note': 'vs last month',
              'trend': '↑ 18.7%',
              'trend_class': 'up'},
             {'icon': 'backoffice/components/icons/icon_0.html',
              'color': 'purple',
              'label': 'Discount Given',
              'value': '৳ 148K',
              'note': 'vs last month',
              'trend': '↑ 14.2%',
              'trend_class': 'up'},
             {'icon': 'backoffice/components/icons/icon_8.html',
              'color': 'orange',
              'label': 'Revenue Influenced',
              'value': '৳ 1.18M',
              'note': 'vs last month',
              'trend': '↑ 19.4%',
              'trend_class': 'up'}],
 'customer_detail': [],
 'customer_add': [],
 'customers': [{'icon': 'backoffice/components/icons/icon_2.html',
                'color': 'purple',
                'label': 'Total Customers',
                'value': '9,672',
                'note': 'vs last month',
                'trend': '↑ 14.2%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_9.html',
                'color': 'green',
                'label': 'New Customers',
                'value': '1,284',
                'note': 'vs last month',
                'trend': '↑ 18.6%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_3.html',
                'color': 'blue',
                'label': 'Repeat Buyers',
                'value': '2,356',
                'note': 'vs last month',
                'trend': '↑ 12.1%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_0.html',
                'color': 'orange',
                'label': 'Average Order Value',
                'value': '৳ 12,850',
                'note': 'vs last month',
                'trend': '↑ 8.3%',
                'trend_class': 'up'}],
 'dashboard': [{'icon': 'backoffice/components/icons/icon_3.html',
                'color': 'green',
                'label': 'Total Sales',
                'value': '৳ 1,248,320',
                'note': 'vs last month',
                'trend': '↑ 12.5%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_10.html',
                'color': 'blue',
                'label': 'Total Orders',
                'value': '1,842',
                'note': 'vs last month',
                'trend': '↑ 8.3%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_2.html',
                'color': 'purple',
                'label': 'Total Customers',
                'value': '9,672',
                'note': 'vs last month',
                'trend': '↑ 14.2%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_11.html',
                'color': 'orange',
                'label': 'Conversion Rate',
                'value': '3.6%',
                'note': 'vs last month',
                'trend': '↑ 0.8%',
                'trend_class': 'up'}],
 'expense_add': [],
 'expenses': [{'icon': 'backoffice/components/icons/icon_0.html',
               'color': 'red',
               'label': 'This Month',
               'value': '৳ 892,450',
               'note': 'vs last month',
               'trend': '↑ 6.8%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_1.html',
               'color': 'orange',
               'label': 'Rent & Utilities',
               'value': '৳ 214,000',
               'note': 'vs last month',
               'trend': '↑ 2.2%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_8.html',
               'color': 'purple',
               'label': 'Marketing',
               'value': '৳ 165,500',
               'note': 'vs last month',
               'trend': '↑ 14.0%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_12.html',
               'color': 'blue',
               'label': 'Courier',
               'value': '৳ 98,750',
               'note': 'vs last month',
               'trend': '↑ 5.2%',
               'trend_class': 'up'}],
 'inventory': [{'icon': 'backoffice/components/icons/icon_5.html',
                'color': 'blue',
                'label': 'Total SKUs',
                'value': '1,248',
                'note': 'vs last month',
                'trend': '↑ 6.1%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_5.html',
                'color': 'green',
                'label': 'In Stock',
                'value': '1,082',
                'note': 'vs last month',
                'trend': '↑ 8.3%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_4.html',
                'color': 'orange',
                'label': 'Low Stock',
                'value': '112',
                'note': 'vs last month',
                'trend': '↑ 12.0%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_5.html',
                'color': 'red',
                'label': 'Out of Stock',
                'value': '54',
                'note': 'vs last month',
                'trend': '↑ 24.3%',
                'trend_class': 'up'}],
 'marketing': [{'icon': 'backoffice/components/icons/icon_8.html',
                'color': 'green',
                'label': 'Active Campaigns',
                'value': '8',
                'note': 'vs last month',
                'trend': '↑ 25%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_5.html',
                'color': 'blue',
                'label': 'Coupon Uses',
                'value': '2,468',
                'note': 'vs last month',
                'trend': '↑ 18.7%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_3.html',
                'color': 'purple',
                'label': 'Conversion Uplift',
                'value': '12.6%',
                'note': 'vs last month',
                'trend': '↑ 3.4%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_2.html',
                'color': 'orange',
                'label': 'Subscribers',
                'value': '9,840',
                'note': 'vs last month',
                'trend': '↑ 22.1%',
                'trend_class': 'up'}],
 'notifications': [],
 'order_detail': [],
 'order_add': [],
 'orders': [{'icon': 'backoffice/components/icons/icon_13.html',
             'color': 'blue',
             'label': 'Total Orders',
             'value': '1,842',
             'note': 'vs last month',
             'trend': '↑ 8.3%',
             'trend_class': 'up'},
            {'icon': 'backoffice/components/icons/icon_14.html',
             'color': 'orange',
             'label': 'Pending',
             'value': '248',
             'note': 'vs last month',
             'trend': '↑ 12.6%',
             'trend_class': 'up'},
            {'icon': 'backoffice/components/icons/icon_5.html',
             'color': 'purple',
             'label': 'Processing',
             'value': '312',
             'note': 'vs last month',
             'trend': '↑ 4.2%',
             'trend_class': 'up'},
            {'icon': 'backoffice/components/icons/icon_12.html',
             'color': 'green',
             'label': 'Delivered',
             'value': '1,320',
             'note': 'vs last month',
             'trend': '↑ 14.2%',
             'trend_class': 'up'}],
 'payment_add': [],
 'payments': [{'icon': 'backoffice/components/icons/icon_0.html',
               'color': 'green',
               'label': 'Money In',
               'value': '৳ 1.42M',
               'note': 'vs last month',
               'trend': '↑ 10.2%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_0.html',
               'color': 'red',
               'label': 'Money Out',
               'value': '৳ 892K',
               'note': 'vs last month',
               'trend': '↑ 6.8%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_14.html',
               'color': 'orange',
               'label': 'Pending',
               'value': '৳ 82K',
               'note': 'vs last month',
               'trend': '↑ 3.1%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_1.html',
               'color': 'purple',
               'label': 'Gateway Clearing',
               'value': '৳ 148K',
               'note': 'vs last month',
               'trend': '↑ 8.7%',
               'trend_class': 'up'}],
 'pos': [],
 'product_edit': [],
 'product_add': [],
 'products': [{'icon': 'backoffice/components/icons/icon_15.html',
               'color': 'green',
               'label': 'Total Products',
               'value': '248',
               'note': 'vs last month',
               'trend': '↑ 12.5%',
               'trend_class': 'up',
               'hook': 'total'},
              {'icon': 'backoffice/components/icons/icon_16.html',
               'color': 'blue',
               'label': 'Active Products',
               'value': '216',
               'note': 'vs last month',
               'trend': '↑ 8.3%',
               'trend_class': 'up',
               'hook': 'active'},
              {'icon': 'backoffice/components/icons/icon_17.html',
               'color': 'red',
               'label': 'Out of Stock',
               'value': '18',
               'note': 'vs last month',
               'trend': '↑ 20.0%',
               'trend_class': 'up',
               'hook': 'out'},
              {'icon': 'backoffice/components/icons/icon_18.html',
               'color': 'purple',
               'label': 'Draft Products',
               'value': '14',
               'note': 'vs last month',
               'trend': '↑ 7.7%',
               'trend_class': 'up',
               'hook': 'draft'}],
 'purchase_add': [],
 'purchases': [{'icon': 'backoffice/components/icons/icon_13.html',
                'color': 'green',
                'label': 'Purchase Orders',
                'value': '186',
                'note': 'vs last month',
                'trend': '↑ 12.5%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_14.html',
                'color': 'orange',
                'label': 'Pending Approvals',
                'value': '24',
                'note': 'vs last month',
                'trend': '↑ 33.3%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_12.html',
                'color': 'purple',
                'label': 'Goods Received',
                'value': '142',
                'note': 'vs last month',
                'trend': '↑ 18.2%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_1.html',
                'color': 'red',
                'label': 'Supplier Due',
                'value': '৳ 248,500',
                'note': 'vs last month',
                'trend': '↑ 10.4%',
                'trend_class': 'up'}],
 'reports': [{'icon': 'backoffice/components/icons/icon_3.html',
              'color': 'green',
              'label': 'Revenue',
              'value': '৳ 1,248,320',
              'note': 'vs last month',
              'trend': '↑ 12.5%',
              'trend_class': 'up'},
             {'icon': 'backoffice/components/icons/icon_13.html',
              'color': 'blue',
              'label': 'Orders',
              'value': '1,842',
              'note': 'vs last month',
              'trend': '↑ 8.3%',
              'trend_class': 'up'},
             {'icon': 'backoffice/components/icons/icon_2.html',
              'color': 'purple',
              'label': 'Customers',
              'value': '9,672',
              'note': 'vs last month',
              'trend': '↑ 14.2%',
              'trend_class': 'up'},
             {'icon': 'backoffice/components/icons/icon_3.html',
              'color': 'orange',
              'label': 'Repeat Purchase',
              'value': '28.6%',
              'note': 'vs last month',
              'trend': '↑ 4.8%',
              'trend_class': 'up'},
             {'icon': 'backoffice/components/icons/icon_3.html',
              'color': 'red',
              'label': 'Conversion Rate',
              'value': '3.6%',
              'note': 'vs last month',
              'trend': '↑ 0.8%',
              'trend_class': 'up'}],
 'return_add': [],
 'returns': [{'icon': 'backoffice/components/icons/icon_19.html',
              'color': 'blue',
              'label': 'Return Requests',
              'value': '86',
              'note': 'vs last month',
              'trend': '↑ 12.5%',
              'trend_class': 'up'},
             {'icon': 'backoffice/components/icons/icon_7.html',
              'color': 'green',
              'label': 'Approved',
              'value': '54',
              'note': 'vs last month',
              'trend': '↑ 18.7%',
              'trend_class': 'up'},
             {'icon': 'backoffice/components/icons/icon_1.html',
              'color': 'purple',
              'label': 'Refunded',
              'value': '48',
              'note': 'vs last month',
              'trend': '↑ 14.2%',
              'trend_class': 'up'},
             {'icon': 'backoffice/components/icons/icon_4.html',
              'color': 'red',
              'label': 'Rejected',
              'value': '18',
              'note': 'vs last month',
              'trend': '↑ 5.6%',
              'trend_class': 'up'}],
 'serial_add': [],
 'serials': [{'icon': 'backoffice/components/icons/icon_5.html',
              'color': 'blue',
              'label': 'Tracked Units',
              'value': '1,862',
              'note': 'vs last month',
              'trend': '↑ 9.4%',
              'trend_class': 'up'},
             {'icon': 'backoffice/components/icons/icon_5.html',
              'color': 'green',
              'label': 'In Stock',
              'value': '1,084',
              'note': 'vs last month',
              'trend': '↑ 5.2%',
              'trend_class': 'up'},
             {'icon': 'backoffice/components/icons/icon_13.html',
              'color': 'purple',
              'label': 'Sold Units',
              'value': '728',
              'note': 'vs last month',
              'trend': '↑ 11.7%',
              'trend_class': 'up'},
             {'icon': 'backoffice/components/icons/icon_20.html',
              'color': 'orange',
              'label': 'Warranty Service',
              'value': '50',
              'note': 'vs last month',
              'trend': '↑ 3.1%',
              'trend_class': 'up'}],
 'settings': [],
 'shipment_add': [],
 'shipping': [{'icon': 'backoffice/components/icons/icon_14.html',
               'color': 'orange',
               'label': 'Pending',
               'value': '248',
               'note': 'vs last month',
               'trend': '↑ 12.6%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_12.html',
               'color': 'blue',
               'label': 'In Transit',
               'value': '612',
               'note': 'vs last month',
               'trend': '↑ 8.3%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_7.html',
               'color': 'green',
               'label': 'Delivered',
               'value': '4,832',
               'note': 'vs last month',
               'trend': '↑ 14.2%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_19.html',
               'color': 'red',
               'label': 'Failed / Returned',
               'value': '220',
               'note': 'vs last month',
               'trend': '↑ 5.1%',
               'trend_class': 'up'}],
 'stock_adjustment': [],
 'stock_transfer': [],
 'supplier_add': [],
 'suppliers': [{'icon': 'backoffice/components/icons/icon_2.html',
                'color': 'blue',
                'label': 'Total Suppliers',
                'value': '36',
                'note': 'vs last month',
                'trend': '↑ 6.4%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_7.html',
                'color': 'green',
                'label': 'Active Suppliers',
                'value': '31',
                'note': 'vs last month',
                'trend': '↑ 4.2%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_1.html',
                'color': 'red',
                'label': 'Outstanding',
                'value': '৳ 312,750',
                'note': 'vs last month',
                'trend': '↑ 4.1%',
                'trend_class': 'up'},
               {'icon': 'backoffice/components/icons/icon_10.html',
                'color': 'purple',
                'label': 'Purchases This Month',
                'value': '৳ 860,000',
                'note': 'vs last month',
                'trend': '↑ 10.8%',
                'trend_class': 'up'}],
 'user_add': [],
 'users': [{'icon': 'backoffice/components/icons/icon_2.html',
            'color': 'blue',
            'label': 'Total Staff',
            'value': '28',
            'note': 'vs last month',
            'trend': '↑ 12.5%',
            'trend_class': 'up'},
           {'icon': 'backoffice/components/icons/icon_7.html',
            'color': 'green',
            'label': 'Active Users',
            'value': '24',
            'note': 'vs last month',
            'trend': '↑ 9.1%',
            'trend_class': 'up'},
           {'icon': 'backoffice/components/icons/icon_20.html',
            'color': 'purple',
            'label': 'Admin Roles',
            'value': '6',
            'note': 'vs last month',
            'trend': '↑ 20%',
            'trend_class': 'up'},
           {'icon': 'backoffice/components/icons/icon_14.html',
            'color': 'orange',
            'label': 'Pending Invitations',
            'value': '4',
            'note': 'vs last month',
            'trend': '↑ 33.3%',
            'trend_class': 'up'}],
 'warehouse_add': [],
 'warehouses': [{'icon': 'backoffice/components/icons/icon_5.html',
                 'color': 'blue',
                 'label': 'Warehouses',
                 'value': '4',
                 'note': 'vs last month',
                 'trend': '↑ 0%',
                 'trend_class': 'up'},
                {'icon': 'backoffice/components/icons/icon_5.html',
                 'color': 'green',
                 'label': 'Total Units',
                 'value': '1,248',
                 'note': 'vs last month',
                 'trend': '↑ 6.1%',
                 'trend_class': 'up'},
                {'icon': 'backoffice/components/icons/icon_0.html',
                 'color': 'purple',
                 'label': 'Stock Value',
                 'value': '৳ 2.8M',
                 'note': 'vs last month',
                 'trend': '↑ 8.0%',
                 'trend_class': 'up'},
                {'icon': 'backoffice/components/icons/icon_21.html',
                 'color': 'orange',
                 'label': 'Transfers Pending',
                 'value': '7',
                 'note': 'vs last week',
                 'trend': '↑ 2',
                 'trend_class': 'up'}],
 'warranty_add': [],
 'warranty': [{'icon': 'backoffice/components/icons/icon_20.html',
               'color': 'blue',
               'label': 'Open Claims',
               'value': '42',
               'note': 'vs last month',
               'trend': '↑ 6.1%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_22.html',
               'color': 'orange',
               'label': 'Under Inspection',
               'value': '18',
               'note': 'vs last month',
               'trend': '↑ 3.2%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_7.html',
               'color': 'green',
               'label': 'Repaired',
               'value': '126',
               'note': 'vs last month',
               'trend': '↑ 11.8%',
               'trend_class': 'up'},
              {'icon': 'backoffice/components/icons/icon_19.html',
               'color': 'purple',
               'label': 'Replacement',
               'value': '24',
               'note': 'vs last month',
               'trend': '↑ 7.0%',
               'trend_class': 'up'}]}

PRODUCTS = SEEDS['products']
ORDERS = SEEDS['orders']
CATEGORIES = SEEDS['categories']
BRANDS = SEEDS['brands']
SERIALS = SEEDS['serials']
CUSTOMERS = SEEDS['customers']
PURCHASES = SEEDS['purchases']
SUPPLIERS = SEEDS['suppliers']
INVENTORY = SEEDS['inventory']
WAREHOUSES = SEEDS['warehouses']
EXPENSES = SEEDS['expenses']
PAYMENTS = SEEDS['payments']
COUPONS = SEEDS['coupons']
SHIPPING = SEEDS['shipping']
RETURNS = SEEDS['returns']
WARRANTY = SEEDS['warranty']
USERS = SEEDS['users']
AUDIT = SEEDS['audit']
