"""Static report, dashboard and form fixtures from the approved demo."""

CUSTOMER_HISTORY = {
    1: [
        {"id": 1, "order_no": "#TB7842", "date_label": "May 23, 2025", "amount": 115000,
         "payment": "bKash", "status": "Delivered", "linked": True},
        {"id": None, "order_no": "#TB7602", "date_label": "Apr 12, 2025", "amount": 8900,
         "payment": "COD", "status": "Delivered", "linked": False},
    ]
}

RECENT_ORDERS = [{'id': 1,
  'order_no': '#TB7842',
  'customer': 'Tanvir Hasan',
  'items': 'iPhone 15 (128GB)',
  'amount': 115000,
  'status': 'Delivered',
  'status_color': 'green',
  'date_label': 'May 23, 2025'},
 {'id': 2,
  'order_no': '#TB7841',
  'customer': 'Sadia Islam',
  'items': 'Sony WH-1000XM5',
  'amount': 42000,
  'status': 'Processing',
  'status_color': 'blue',
  'date_label': 'May 23, 2025'},
 {'id': 3,
  'order_no': '#TB7840',
  'customer': 'Rafiq Ahmed',
  'items': 'HP Laptop 15s',
  'amount': 78500,
  'status': 'Shipped',
  'status_color': 'orange',
  'date_label': 'May 22, 2025'},
 {'id': 4,
  'order_no': '#TB7839',
  'customer': 'Nusrat Jahan',
  'items': 'Redmi Note 13 Pro',
  'amount': 32999,
  'status': 'Delivered',
  'status_color': 'green',
  'date_label': 'May 22, 2025'},
 {'id': 5,
  'order_no': '#TB7838',
  'customer': 'Mehedi Hasan',
  'items': 'Logitech MK345',
  'amount': 4200,
  'status': 'Cancelled',
  'status_color': 'red',
  'date_label': 'May 21, 2025'}]

TOP_PRODUCTS = [{'name': 'iPhone 15 (128GB)',
  'category': 'Smartphones',
  'image': 'admin/images/airpods-pro2.webp',
  'sold': '326',
  'price': 115000},
 {'name': 'Redmi Note 13 Pro',
  'category': 'Smartphones',
  'image': 'admin/images/haylou-rs4.webp',
  'sold': '284',
  'price': 32999},
 {'name': 'Samsung 24” FHD Monitor',
  'category': 'Monitors',
  'image': 'admin/images/jbl-flip6.webp',
  'sold': '192',
  'price': 18500},
 {'name': 'HP Laptop 15s (i5)',
  'category': 'Laptops',
  'image': 'admin/images/xiaomi-powerbank.webp',
  'sold': '176',
  'price': 78500},
 {'name': 'Sony WH-1000XM5',
  'category': 'Audio',
  'image': 'admin/images/q20i.webp',
  'sold': '146',
  'price': 42000}]

ORDER_BREAKDOWN = [{'color': '#12b76a', 'label': 'Delivered', 'count': '1,320', 'percentage': '71.7%'},
 {'color': '#2a8cff', 'label': 'Processing', 'count': '248', 'percentage': '13.5%'},
 {'color': '#ffc12f', 'label': 'Shipped', 'count': '164', 'percentage': '8.9%'},
 {'color': '#ff4c5d', 'label': 'Cancelled', 'count': '72', 'percentage': '3.9%'},
 {'color': '#96a3b7', 'label': 'Returned', 'count': '38', 'percentage': '2.1%'}]

REPORTS = [{'name': 'Sales Summary',
  'description': 'Revenue, discounts, taxes and trends.',
  'icon': 'backoffice/components/icons/report_0.html'},
 {'name': 'Profit & Loss',
  'description': 'Revenue, COGS, expenses and net profit.',
  'icon': 'backoffice/components/icons/report_1.html'},
 {'name': 'Stock Report',
  'description': 'Stock, valuation, aging and low stock.',
  'icon': 'backoffice/components/icons/report_2.html'},
 {'name': 'Purchase Report',
  'description': 'Supplier, PO and cost performance.',
  'icon': 'backoffice/components/icons/report_3.html'},
 {'name': 'Customer Report',
  'description': 'Retention, CLV, due and segments.',
  'icon': 'backoffice/components/icons/report_4.html'},
 {'name': 'Courier Report',
  'description': 'Delivery success, COD and settlements.',
  'icon': 'backoffice/components/icons/report_5.html'},
 {'name': 'Trial Balance',
  'description': 'Debit/credit balances by account.',
  'icon': 'backoffice/components/icons/report_6.html'},
 {'name': 'Balance Sheet',
  'description': 'Assets, liabilities and equity.',
  'icon': 'backoffice/components/icons/report_7.html'},
 {'name': 'Marketing Performance',
  'description': 'Campaign revenue, ROAS and CPA.',
  'icon': 'backoffice/components/icons/report_8.html'}]

FORM_DEFAULTS = {'brand_add': {'description': ''},
 'category_add': {'description': ''},
 'coupon_add': {},
 'customer_add': {'address': ''},
 'expense_add': {'description': ''},
 'order_add': {},
 'payment_add': {},
 'product_edit': {'shortDescription': 'Premium TWS Earbuds with Active Noise Cancellation, USB-C '
                                      'Charging.',
                  'salePrice': '29999',
                  'lowStock': '10',
                  'status': 'Active',
                  'metaTitle': 'AirPods Pro 2 (USB-C) – Premium TWS Earbuds | TechBari',
                  'slug': 'airpods-pro-2-usb-c',
                  'description': 'AirPods Pro 2 (USB-C) deliver up to 2x more Active Noise '
                                 'Cancellation, Adaptive Transparency, and personalized spatial '
                                 'audio. With a USB-C charging case, longer battery life, and a '
                                 'more comfortable fit, they’re the ultimate listening experience '
                                 'for Apple users.',
                  'metaDescription': 'Buy AirPods Pro 2 (USB-C) at the best price in Bangladesh. '
                                     'Premium TWS earbuds with Active Noise Cancellation, USB-C '
                                     'charging and spatial audio. Original Apple product at '
                                     'TechBari.'},
 'product_add': {'name': 'Baseus Bowie E16 TWS Earbuds',
                 'sku': 'TB-BAS-007',
                 'weight': '0.15',
                 'price': '1299',
                 'salePrice': '999',
                 'stock': '100',
                 'lowStock': '10',
                 'shortDescription': 'Powerful sound, long battery life and comfortable fit. '
                                     'Baseus Bowie E16 TWS earbuds deliver exceptional audio '
                                     'experience for everyday use.',
                 'description': 'The Baseus Bowie E16 TWS Earbuds offer an immersive listening '
                                'experience with high-quality sound, deep bass and crystal-clear '
                                'calls. With up to 30 hours of total playtime, Bluetooth 5.3, and '
                                'a comfortable ergonomic design, they are perfect for work, travel '
                                'and everyday use.\\n\\nKey Features:\\n• 13mm dynamic drivers for '
                                'powerful sound\\n• Up to 30 hours total playtime\\n• Bluetooth '
                                '5.3 for stable connection\\n• AI ENC noise cancellation for clear '
                                'calls\\n• IPX4 water resistance\\n• Comfortable and lightweight '
                                'design'},
 'purchase_add': {},
 'return_add': {},
 'serial_add': {},
 'shipment_add': {},
 'stock_adjustment': {'reason': ''},
 'stock_transfer': {},
 'supplier_add': {'address': ''},
 'user_add': {},
 'warehouse_add': {'address': ''},
 'warranty_add': {'issue': ''}}


CAMPAIGNS = [{'color': 'blue',
  'status_color': 'green',
  'status': 'Active',
  'name': 'Eid Tech Deals 2025',
  'description': 'Up to 30% off smart devices',
  'impressions': '125K',
  'ctr': '3.8%',
  'sales': '৳265K'},
 {'color': 'purple',
  'status_color': 'orange',
  'status': 'Scheduled',
  'name': 'Weekend Flash Sale',
  'description': 'Selected audio products',
  'impressions': '0',
  'ctr': '0%',
  'sales': '৳0'},
 {'color': 'cyan',
  'status_color': 'green',
  'status': 'Active',
  'name': 'Back to School',
  'description': 'Tech for a smarter future',
  'impressions': '87K',
  'ctr': '2.9%',
  'sales': '৳198K'}]

NOTIFICATIONS = [{'unread': True,
  'icon': 'backoffice/components/icons/notification_0.html',
  'title': 'New order #TB7842',
  'message': 'Tanvir Hasan placed a new order for ৳115,000.',
  'time': '2 minutes ago'},
 {'unread': True,
  'icon': 'backoffice/components/icons/notification_1.html',
  'title': 'Low stock alert',
  'message': 'Sony WH-1000XM5 has only 8 units remaining.',
  'time': '18 minutes ago'},
 {'unread': False,
  'icon': 'backoffice/components/icons/notification_2.html',
  'title': 'Courier settlement received',
  'message': 'Steadfast settlement of ৳82,500 has been recorded.',
  'time': '1 hour ago'},
 {'unread': False,
  'icon': 'backoffice/components/icons/notification_3.html',
  'title': 'Return request received',
  'message': 'Return #RET7840 needs review.',
  'time': '3 hours ago'}]

STOCK_ALERTS = [{'product': 'Sony WH-1000XM5', 'stock': 8, 'reorder': 15},
 {'product': 'JBL Flip 6', 'stock': 3, 'reorder': 10},
 {'product': 'Canon EOS 2000D', 'stock': 6, 'reorder': 10},
 {'product': 'Logitech MK345', 'stock': 9, 'reorder': 15}]

ACCOUNT_CHART = [{'revenue': 45, 'expenses': 32, 'month': 'Jan'},
 {'revenue': 58, 'expenses': 40, 'month': 'Feb'},
 {'revenue': 64, 'expenses': 46, 'month': 'Mar'},
 {'revenue': 72, 'expenses': 52, 'month': 'Apr'},
 {'revenue': 84, 'expenses': 61, 'month': 'May'},
 {'revenue': 76, 'expenses': 55, 'month': 'Jun'},
 {'revenue': 90, 'expenses': 63, 'month': 'Jul'}]

ACCOUNT_SUMMARY = {'revenue': 1248320, 'expenses': 892450, 'gross_profit': 410680, 'net_profit': 355870}

ORDER_TIMELINE = [{'label': 'Order Placed',
  'description': 'Payment confirmed',
  'time': 'May 23, 2025 \xa0 10:24 AM'},
 {'label': 'Processing',
  'description': 'Order is being prepared',
  'time': 'May 23, 2025 \xa0 11:10 AM'},
 {'label': 'Shipped',
  'description': 'Package handed over to courier',
  'time': 'May 23, 2025 \xa0 04:35 PM'},
 {'label': 'Out for Delivery',
  'description': 'On the way to customer',
  'time': 'May 24, 2025 \xa0 09:12 AM'},
 {'label': 'Delivered',
  'description': 'Order delivered successfully',
  'time': 'May 24, 2025 \xa0 01:28 PM'}]

FORM_OPTIONS = {'brand_add': {'featured': [{'label': 'Yes', 'value': 'Yes', 'has_value': True, 'selected': False},
                            {'label': 'No', 'value': 'No', 'has_value': True, 'selected': False}],
               'status': [{'label': 'Active',
                           'value': 'Active',
                           'has_value': False,
                           'selected': False},
                          {'label': 'Inactive',
                           'value': 'Inactive',
                           'has_value': False,
                           'selected': False},
                          {'label': 'Draft',
                           'value': 'Draft',
                           'has_value': False,
                           'selected': False}]},
 'category_add': {'parent': [{'label': 'None',
                              'value': 'None',
                              'has_value': True,
                              'selected': False},
                             {'label': 'Audio',
                              'value': 'Audio',
                              'has_value': True,
                              'selected': False},
                             {'label': 'Accessories',
                              'value': 'Accessories',
                              'has_value': True,
                              'selected': False},
                             {'label': 'Wearables',
                              'value': 'Wearables',
                              'has_value': True,
                              'selected': False}],
                  'status': [{'label': 'Active',
                              'value': 'Active',
                              'has_value': False,
                              'selected': False},
                             {'label': 'Inactive',
                              'value': 'Inactive',
                              'has_value': False,
                              'selected': False},
                             {'label': 'Draft',
                              'value': 'Draft',
                              'has_value': False,
                              'selected': False}]},
 'coupon_add': {'type': [{'label': 'Percent',
                          'value': 'Percent',
                          'has_value': True,
                          'selected': False},
                         {'label': 'Fixed', 'value': 'Fixed', 'has_value': True, 'selected': False},
                         {'label': 'Free Shipping',
                          'value': 'Free Shipping',
                          'has_value': True,
                          'selected': False}],
                'status': [{'label': 'Active',
                            'value': 'Active',
                            'has_value': False,
                            'selected': False},
                           {'label': 'Inactive',
                            'value': 'Inactive',
                            'has_value': False,
                            'selected': False},
                           {'label': 'Draft',
                            'value': 'Draft',
                            'has_value': False,
                            'selected': False}]},
 'customer_add': {'group': [{'label': 'Regular',
                             'value': 'Regular',
                             'has_value': True,
                             'selected': False},
                            {'label': 'VIP', 'value': 'VIP', 'has_value': True, 'selected': False},
                            {'label': 'Wholesale',
                             'value': 'Wholesale',
                             'has_value': True,
                             'selected': False},
                            {'label': 'Dealer',
                             'value': 'Dealer',
                             'has_value': True,
                             'selected': False}],
                  'status': [{'label': 'Active',
                              'value': 'Active',
                              'has_value': False,
                              'selected': False},
                             {'label': 'Inactive',
                              'value': 'Inactive',
                              'has_value': False,
                              'selected': False},
                             {'label': 'Draft',
                              'value': 'Draft',
                              'has_value': False,
                              'selected': False}]},
 'expense_add': {'category': [{'label': 'Rent',
                               'value': 'Rent',
                               'has_value': True,
                               'selected': False},
                              {'label': 'Salary',
                               'value': 'Salary',
                               'has_value': True,
                               'selected': False},
                              {'label': 'Advertising',
                               'value': 'Advertising',
                               'has_value': True,
                               'selected': False},
                              {'label': 'Courier',
                               'value': 'Courier',
                               'has_value': True,
                               'selected': False},
                              {'label': 'Electricity',
                               'value': 'Electricity',
                               'has_value': True,
                               'selected': False},
                              {'label': 'Internet',
                               'value': 'Internet',
                               'has_value': True,
                               'selected': False},
                              {'label': 'Office',
                               'value': 'Office',
                               'has_value': True,
                               'selected': False}],
                 'method': [{'label': 'Cash',
                             'value': 'Cash',
                             'has_value': True,
                             'selected': False},
                            {'label': 'Bank',
                             'value': 'Bank',
                             'has_value': True,
                             'selected': False},
                            {'label': 'bKash',
                             'value': 'bKash',
                             'has_value': True,
                             'selected': False},
                            {'label': 'Nagad',
                             'value': 'Nagad',
                             'has_value': True,
                             'selected': False}],
                 'status': [{'label': 'Active',
                             'value': 'Active',
                             'has_value': False,
                             'selected': False},
                            {'label': 'Inactive',
                             'value': 'Inactive',
                             'has_value': False,
                             'selected': False},
                            {'label': 'Draft',
                             'value': 'Draft',
                             'has_value': False,
                             'selected': False}]},
 'stock_adjustment': {'warehouse': [{'label': 'Main Warehouse',
                                     'value': 'Main Warehouse',
                                     'has_value': True,
                                     'selected': False},
                                    {'label': 'Dhanmondi Store',
                                     'value': 'Dhanmondi Store',
                                     'has_value': True,
                                     'selected': False},
                                    {'label': 'Uttara Store',
                                     'value': 'Uttara Store',
                                     'has_value': True,
                                     'selected': False}],
                      'status': [{'label': 'Active',
                                  'value': 'Active',
                                  'has_value': False,
                                  'selected': False},
                                 {'label': 'Inactive',
                                  'value': 'Inactive',
                                  'has_value': False,
                                  'selected': False},
                                 {'label': 'Draft',
                                  'value': 'Draft',
                                  'has_value': False,
                                  'selected': False}]},
 'stock_transfer': {'from': [{'label': 'Main Warehouse',
                              'value': 'Main Warehouse',
                              'has_value': True,
                              'selected': False},
                             {'label': 'Dhanmondi Store',
                              'value': 'Dhanmondi Store',
                              'has_value': True,
                              'selected': False},
                             {'label': 'Uttara Store',
                              'value': 'Uttara Store',
                              'has_value': True,
                              'selected': False}],
                    'to': [{'label': 'Main Warehouse',
                            'value': 'Main Warehouse',
                            'has_value': True,
                            'selected': False},
                           {'label': 'Dhanmondi Store',
                            'value': 'Dhanmondi Store',
                            'has_value': True,
                            'selected': False},
                           {'label': 'Uttara Store',
                            'value': 'Uttara Store',
                            'has_value': True,
                            'selected': False}],
                    'status': [{'label': 'Active',
                                'value': 'Active',
                                'has_value': False,
                                'selected': False},
                               {'label': 'Inactive',
                                'value': 'Inactive',
                                'has_value': False,
                                'selected': False},
                               {'label': 'Draft',
                                'value': 'Draft',
                                'has_value': False,
                                'selected': False}]},
 'order_add': {'payment': [{'label': 'Cash on Delivery',
                            'value': 'Cash on Delivery',
                            'has_value': True,
                            'selected': False},
                           {'label': 'bKash',
                            'value': 'bKash',
                            'has_value': True,
                            'selected': False},
                           {'label': 'Nagad',
                            'value': 'Nagad',
                            'has_value': True,
                            'selected': False},
                           {'label': 'Card',
                            'value': 'Card',
                            'has_value': True,
                            'selected': False}],
               'status': [{'label': 'Active',
                           'value': 'Active',
                           'has_value': False,
                           'selected': False},
                          {'label': 'Inactive',
                           'value': 'Inactive',
                           'has_value': False,
                           'selected': False},
                          {'label': 'Draft',
                           'value': 'Draft',
                           'has_value': False,
                           'selected': False}]},
 'payment_add': {'type': [{'label': 'Income',
                           'value': 'Income',
                           'has_value': True,
                           'selected': False},
                          {'label': 'Expense',
                           'value': 'Expense',
                           'has_value': True,
                           'selected': False},
                          {'label': 'Transfer',
                           'value': 'Transfer',
                           'has_value': True,
                           'selected': False},
                          {'label': 'Refund',
                           'value': 'Refund',
                           'has_value': True,
                           'selected': False}],
                 'method': [{'label': 'Cash',
                             'value': 'Cash',
                             'has_value': True,
                             'selected': False},
                            {'label': 'Bank',
                             'value': 'Bank',
                             'has_value': True,
                             'selected': False},
                            {'label': 'bKash',
                             'value': 'bKash',
                             'has_value': True,
                             'selected': False},
                            {'label': 'Nagad',
                             'value': 'Nagad',
                             'has_value': True,
                             'selected': False},
                            {'label': 'Card',
                             'value': 'Card',
                             'has_value': True,
                             'selected': False}],
                 'status': [{'label': 'Active',
                             'value': 'Active',
                             'has_value': False,
                             'selected': False},
                            {'label': 'Inactive',
                             'value': 'Inactive',
                             'has_value': False,
                             'selected': False},
                            {'label': 'Draft',
                             'value': 'Draft',
                             'has_value': False,
                             'selected': False}]},
 'product_add': {'shippingClass': [{'label': 'Standard',
                                    'value': 'Standard',
                                    'has_value': False,
                                    'selected': False},
                                   {'label': 'Fragile',
                                    'value': 'Fragile',
                                    'has_value': False,
                                    'selected': False},
                                   {'label': 'Oversize',
                                    'value': 'Oversize',
                                    'has_value': False,
                                    'selected': False}],
                 'category': [{'label': 'Earbuds',
                               'value': 'Earbuds',
                               'has_value': False,
                               'selected': False},
                              {'label': 'Headphones',
                               'value': 'Headphones',
                               'has_value': False,
                               'selected': False},
                              {'label': 'Speakers',
                               'value': 'Speakers',
                               'has_value': False,
                               'selected': False},
                              {'label': 'Smartwatches',
                               'value': 'Smartwatches',
                               'has_value': False,
                               'selected': False},
                              {'label': 'Power Banks',
                               'value': 'Power Banks',
                               'has_value': False,
                               'selected': False}],
                 'brand': [{'label': 'Baseus',
                            'value': 'Baseus',
                            'has_value': False,
                            'selected': False},
                           {'label': 'Apple',
                            'value': 'Apple',
                            'has_value': False,
                            'selected': False},
                           {'label': 'Sony',
                            'value': 'Sony',
                            'has_value': False,
                            'selected': False},
                           {'label': 'JBL', 'value': 'JBL', 'has_value': False, 'selected': False},
                           {'label': 'Anker',
                            'value': 'Anker',
                            'has_value': False,
                            'selected': False}],
                 'warranty': [{'label': '6 Months',
                               'value': '6 Months',
                               'has_value': False,
                               'selected': False},
                              {'label': '12 Months',
                               'value': '12 Months',
                               'has_value': False,
                               'selected': False},
                              {'label': 'No Warranty',
                               'value': 'No Warranty',
                               'has_value': False,
                               'selected': False}],
                 'status': [{'label': 'Active',
                             'value': 'Active',
                             'has_value': False,
                             'selected': False},
                            {'label': 'Draft',
                             'value': 'Draft',
                             'has_value': False,
                             'selected': False},
                            {'label': 'Archived',
                             'value': 'Archived',
                             'has_value': False,
                             'selected': False}]},
 'product_edit': {'category': [{'label': 'TWS Earbuds',
                                'value': 'TWS Earbuds',
                                'has_value': False,
                                'selected': False},
                               {'label': 'Earbuds',
                                'value': 'Earbuds',
                                'has_value': False,
                                'selected': False},
                               {'label': 'Headphones',
                                'value': 'Headphones',
                                'has_value': False,
                                'selected': False},
                               {'label': 'Speakers',
                                'value': 'Speakers',
                                'has_value': False,
                                'selected': False},
                               {'label': 'Smartwatches',
                                'value': 'Smartwatches',
                                'has_value': False,
                                'selected': False},
                               {'label': 'Power Banks',
                                'value': 'Power Banks',
                                'has_value': False,
                                'selected': False}],
                  'brand': [{'label': 'Apple',
                             'value': 'Apple',
                             'has_value': False,
                             'selected': False},
                            {'label': 'Baseus',
                             'value': 'Baseus',
                             'has_value': False,
                             'selected': False},
                            {'label': 'Sony',
                             'value': 'Sony',
                             'has_value': False,
                             'selected': False},
                            {'label': 'JBL', 'value': 'JBL', 'has_value': False, 'selected': False},
                            {'label': 'Anker',
                             'value': 'Anker',
                             'has_value': False,
                             'selected': False},
                            {'label': 'Samsung',
                             'value': 'Samsung',
                             'has_value': False,
                             'selected': False}]},
 'purchase_add': {'supplier': [{'label': 'Transcom Digital',
                                'value': 'Transcom Digital',
                                'has_value': True,
                                'selected': False},
                               {'label': 'Star Tech Ltd.',
                                'value': 'Star Tech Ltd.',
                                'has_value': True,
                                'selected': False},
                               {'label': 'RYANS Computers',
                                'value': 'RYANS Computers',
                                'has_value': True,
                                'selected': False},
                               {'label': 'UCC International',
                                'value': 'UCC International',
                                'has_value': True,
                                'selected': False}],
                  'warehouse': [{'label': 'Main Warehouse',
                                 'value': 'Main Warehouse',
                                 'has_value': True,
                                 'selected': False},
                                {'label': 'Dhanmondi Store',
                                 'value': 'Dhanmondi Store',
                                 'has_value': True,
                                 'selected': False},
                                {'label': 'Uttara Store',
                                 'value': 'Uttara Store',
                                 'has_value': True,
                                 'selected': False}],
                  'payment': [{'label': 'Pending',
                               'value': 'Pending',
                               'has_value': True,
                               'selected': False},
                              {'label': 'Partial',
                               'value': 'Partial',
                               'has_value': True,
                               'selected': False},
                              {'label': 'Paid',
                               'value': 'Paid',
                               'has_value': True,
                               'selected': False}],
                  'status': [{'label': 'Active',
                              'value': 'Active',
                              'has_value': False,
                              'selected': False},
                             {'label': 'Inactive',
                              'value': 'Inactive',
                              'has_value': False,
                              'selected': False},
                             {'label': 'Draft',
                              'value': 'Draft',
                              'has_value': False,
                              'selected': False}]},
 'return_add': {'reason': [{'label': 'Defective item',
                            'value': 'Defective item',
                            'has_value': True,
                            'selected': False},
                           {'label': 'Changed mind',
                            'value': 'Changed mind',
                            'has_value': True,
                            'selected': False},
                           {'label': 'Wrong item',
                            'value': 'Wrong item',
                            'has_value': True,
                            'selected': False},
                           {'label': 'Not as described',
                            'value': 'Not as described',
                            'has_value': True,
                            'selected': False},
                           {'label': 'Damaged',
                            'value': 'Damaged',
                            'has_value': True,
                            'selected': False}],
                'status': [{'label': 'Active',
                            'value': 'Active',
                            'has_value': False,
                            'selected': False},
                           {'label': 'Inactive',
                            'value': 'Inactive',
                            'has_value': False,
                            'selected': False},
                           {'label': 'Draft',
                            'value': 'Draft',
                            'has_value': False,
                            'selected': False}]},
 'serial_add': {'warehouse': [{'label': 'Main Warehouse',
                               'value': 'Main Warehouse',
                               'has_value': True,
                               'selected': False},
                              {'label': 'Dhanmondi Store',
                               'value': 'Dhanmondi Store',
                               'has_value': True,
                               'selected': False},
                              {'label': 'Uttara Store',
                               'value': 'Uttara Store',
                               'has_value': True,
                               'selected': False}],
                'status': [{'label': 'Active',
                            'value': 'Active',
                            'has_value': False,
                            'selected': False},
                           {'label': 'Inactive',
                            'value': 'Inactive',
                            'has_value': False,
                            'selected': False},
                           {'label': 'Draft',
                            'value': 'Draft',
                            'has_value': False,
                            'selected': False}]},
 'shipment_add': {'courier': [{'label': 'Steadfast',
                               'value': 'Steadfast',
                               'has_value': True,
                               'selected': False},
                              {'label': 'Pathao',
                               'value': 'Pathao',
                               'has_value': True,
                               'selected': False},
                              {'label': 'RedX',
                               'value': 'RedX',
                               'has_value': True,
                               'selected': False},
                              {'label': 'Sundarban',
                               'value': 'Sundarban',
                               'has_value': True,
                               'selected': False}],
                  'status': [{'label': 'Active',
                              'value': 'Active',
                              'has_value': False,
                              'selected': False},
                             {'label': 'Inactive',
                              'value': 'Inactive',
                              'has_value': False,
                              'selected': False},
                             {'label': 'Draft',
                              'value': 'Draft',
                              'has_value': False,
                              'selected': False}]},
 'supplier_add': {'terms': [{'label': 'Due on Receipt',
                             'value': 'Due on Receipt',
                             'has_value': True,
                             'selected': False},
                            {'label': '7 Days',
                             'value': '7 Days',
                             'has_value': True,
                             'selected': False},
                            {'label': '15 Days',
                             'value': '15 Days',
                             'has_value': True,
                             'selected': False},
                            {'label': '30 Days',
                             'value': '30 Days',
                             'has_value': True,
                             'selected': False}],
                  'status': [{'label': 'Active',
                              'value': 'Active',
                              'has_value': False,
                              'selected': False},
                             {'label': 'Inactive',
                              'value': 'Inactive',
                              'has_value': False,
                              'selected': False},
                             {'label': 'Draft',
                              'value': 'Draft',
                              'has_value': False,
                              'selected': False}]},
 'user_add': {'role': [{'label': 'Super Admin',
                        'value': 'Super Admin',
                        'has_value': True,
                        'selected': False},
                       {'label': 'Manager',
                        'value': 'Manager',
                        'has_value': True,
                        'selected': False},
                       {'label': 'Accountant',
                        'value': 'Accountant',
                        'has_value': True,
                        'selected': False},
                       {'label': 'Cashier',
                        'value': 'Cashier',
                        'has_value': True,
                        'selected': False},
                       {'label': 'Order Manager',
                        'value': 'Order Manager',
                        'has_value': True,
                        'selected': False},
                       {'label': 'Inventory Manager',
                        'value': 'Inventory Manager',
                        'has_value': True,
                        'selected': False},
                       {'label': 'Customer Support',
                        'value': 'Customer Support',
                        'has_value': True,
                        'selected': False}],
              'branch': [{'label': 'Head Office',
                          'value': 'Head Office',
                          'has_value': True,
                          'selected': False},
                         {'label': 'Dhanmondi',
                          'value': 'Dhanmondi',
                          'has_value': True,
                          'selected': False},
                         {'label': 'Uttara',
                          'value': 'Uttara',
                          'has_value': True,
                          'selected': False},
                         {'label': 'Chattogram',
                          'value': 'Chattogram',
                          'has_value': True,
                          'selected': False}],
              'status': [{'label': 'Active',
                          'value': 'Active',
                          'has_value': False,
                          'selected': False},
                         {'label': 'Inactive',
                          'value': 'Inactive',
                          'has_value': False,
                          'selected': False},
                         {'label': 'Draft',
                          'value': 'Draft',
                          'has_value': False,
                          'selected': False}]},
 'warehouse_add': {'branch': [{'label': 'Head Office',
                               'value': 'Head Office',
                               'has_value': True,
                               'selected': False},
                              {'label': 'Dhanmondi',
                               'value': 'Dhanmondi',
                               'has_value': True,
                               'selected': False},
                              {'label': 'Uttara',
                               'value': 'Uttara',
                               'has_value': True,
                               'selected': False},
                              {'label': 'Chattogram',
                               'value': 'Chattogram',
                               'has_value': True,
                               'selected': False}],
                   'status': [{'label': 'Active',
                               'value': 'Active',
                               'has_value': False,
                               'selected': False},
                              {'label': 'Inactive',
                               'value': 'Inactive',
                               'has_value': False,
                               'selected': False},
                              {'label': 'Draft',
                               'value': 'Draft',
                               'has_value': False,
                               'selected': False}]},
 'warranty_add': {'resolution': [{'label': 'Repair',
                                  'value': 'Repair',
                                  'has_value': True,
                                  'selected': False},
                                 {'label': 'Replace',
                                  'value': 'Replace',
                                  'has_value': True,
                                  'selected': False},
                                 {'label': 'Refund',
                                  'value': 'Refund',
                                  'has_value': True,
                                  'selected': False},
                                 {'label': 'Reject',
                                  'value': 'Reject',
                                  'has_value': True,
                                  'selected': False}],
                  'status': [{'label': 'Active',
                              'value': 'Active',
                              'has_value': False,
                              'selected': False},
                             {'label': 'Inactive',
                              'value': 'Inactive',
                              'has_value': False,
                              'selected': False},
                             {'label': 'Draft',
                              'value': 'Draft',
                              'has_value': False,
                              'selected': False}]}}
