"""Named static pages and their approved sidebar selection."""

PAGES = {'accounts': {'path': 'accounts/',
              'template': 'backoffice/pages/accounts/accounts.html',
              'legacy': 'accounts',
              'section': 'accounts'},
 'audit_log': {'path': 'audit-log/',
               'template': 'backoffice/pages/audit/audit_log.html',
               'legacy': 'audit-log',
               'section': 'users'},
 'brand_add': {'path': 'brands/add/',
               'template': 'backoffice/pages/brands/brand_add.html',
               'legacy': 'brand-form',
               'section': 'products'},
 'brands': {'path': 'brands/',
            'template': 'backoffice/pages/brands/brands.html',
            'legacy': 'brands',
            'section': 'products'},
 'categories': {'path': 'categories/',
                'template': 'backoffice/pages/categories/categories.html',
                'legacy': 'categories',
                'section': 'products'},
 'category_add': {'path': 'categories/add/',
                  'template': 'backoffice/pages/categories/category_add.html',
                  'legacy': 'category-form',
                  'section': 'products'},
 'coupon_add': {'path': 'coupons/add/',
                'template': 'backoffice/pages/coupons/coupon_add.html',
                'legacy': 'coupon-form',
                'section': 'marketing'},
 'coupons': {'path': 'coupons/',
             'template': 'backoffice/pages/coupons/coupons.html',
             'legacy': 'coupons',
             'section': 'marketing'},
 'customer_detail': {'path': 'customers/detail/',
                     'template': 'backoffice/pages/customers/customer_detail.html',
                     'legacy': 'customer-details',
                     'section': 'customers'},
 'customer_add': {'path': 'customers/add/',
                  'template': 'backoffice/pages/customers/customer_add.html',
                  'legacy': 'customer-form',
                  'section': 'customers'},
 'customers': {'path': 'customers/',
               'template': 'backoffice/pages/customers/customers.html',
               'legacy': 'customers',
               'section': 'customers'},
 'dashboard': {'path': '',
               'template': 'backoffice/pages/dashboard.html',
               'legacy': 'dashboard',
               'section': 'dashboard'},
 'expense_add': {'path': 'expenses/add/',
                 'template': 'backoffice/pages/expenses/expense_add.html',
                 'legacy': 'expense-form',
                 'section': 'accounts'},
 'expenses': {'path': 'expenses/',
              'template': 'backoffice/pages/expenses/expenses.html',
              'legacy': 'expenses',
              'section': 'accounts'},
 'inventory': {'path': 'inventory/',
               'template': 'backoffice/pages/inventory/inventory.html',
               'legacy': 'inventory',
               'section': 'inventory'},
 'marketing': {'path': 'marketing/',
               'template': 'backoffice/pages/marketing/marketing.html',
               'legacy': 'marketing',
               'section': 'marketing'},
 'notifications': {'path': 'notifications/',
                   'template': 'backoffice/pages/notifications/notifications.html',
                   'legacy': 'notifications',
                   'section': 'dashboard'},
 'order_detail': {'path': 'orders/detail/',
                  'template': 'backoffice/pages/orders/order_detail.html',
                  'legacy': 'order-details',
                  'section': 'orders'},
 'order_add': {'path': 'orders/add/',
               'template': 'backoffice/pages/orders/order_add.html',
               'legacy': 'order-form',
               'section': 'orders'},
 'orders': {'path': 'orders/',
            'template': 'backoffice/pages/orders/orders.html',
            'legacy': 'orders',
            'section': 'orders'},
 'payment_add': {'path': 'payments/add/',
                 'template': 'backoffice/pages/payments/payment_add.html',
                 'legacy': 'payment-form',
                 'section': 'accounts'},
 'payments': {'path': 'payments/',
              'template': 'backoffice/pages/payments/payments.html',
              'legacy': 'payments',
              'section': 'accounts'},
 'pos': {'path': 'pos/',
         'template': 'backoffice/pages/pos/pos.html',
         'legacy': 'pos',
         'section': 'pos'},
 'product_edit': {'path': 'products/edit/',
                  'template': 'backoffice/pages/products/product_edit.html',
                  'legacy': 'product-edit',
                  'section': 'products'},
 'product_add': {'path': 'products/add/',
                 'template': 'backoffice/pages/products/product_add.html',
                 'legacy': 'product-form',
                 'section': 'products'},
 'products': {'path': 'products/',
              'template': 'backoffice/pages/products/products.html',
              'legacy': 'products',
              'section': 'products'},
 'purchase_add': {'path': 'purchases/add/',
                  'template': 'backoffice/pages/purchases/purchase_add.html',
                  'legacy': 'purchase-form',
                  'section': 'purchases'},
 'purchases': {'path': 'purchases/',
               'template': 'backoffice/pages/purchases/purchases.html',
               'legacy': 'purchases',
               'section': 'purchases'},
 'reports': {'path': 'reports/',
             'template': 'backoffice/pages/reports/reports.html',
             'legacy': 'reports',
             'section': 'reports'},
 'return_add': {'path': 'returns/add/',
                'template': 'backoffice/pages/returns/return_add.html',
                'legacy': 'return-form',
                'section': 'returns'},
 'returns': {'path': 'returns/',
             'template': 'backoffice/pages/returns/returns.html',
             'legacy': 'returns',
             'section': 'returns'},
 'serial_add': {'path': 'serials/add/',
                'template': 'backoffice/pages/serials/serial_add.html',
                'legacy': 'serial-form',
                'section': 'products'},
 'serials': {'path': 'serials/',
             'template': 'backoffice/pages/serials/serials.html',
             'legacy': 'serials',
             'section': 'products'},
 'settings': {'path': 'settings/',
              'template': 'backoffice/pages/settings/settings.html',
              'legacy': 'settings',
              'section': 'settings'},
 'shipment_add': {'path': 'shipping/add/',
                  'template': 'backoffice/pages/shipping/shipment_add.html',
                  'legacy': 'shipment-form',
                  'section': 'shipping'},
 'shipping': {'path': 'shipping/',
              'template': 'backoffice/pages/shipping/shipping.html',
              'legacy': 'shipping',
              'section': 'shipping'},
 'stock_adjustment': {'path': 'stock-adjustment/',
                      'template': 'backoffice/pages/inventory/stock_adjustment.html',
                      'legacy': 'stock-adjustment',
                      'section': 'inventory'},
 'stock_transfer': {'path': 'stock-transfer/',
                    'template': 'backoffice/pages/inventory/stock_transfer.html',
                    'legacy': 'stock-transfer',
                    'section': 'inventory'},
 'supplier_add': {'path': 'suppliers/add/',
                  'template': 'backoffice/pages/suppliers/supplier_add.html',
                  'legacy': 'supplier-form',
                  'section': 'purchases'},
 'suppliers': {'path': 'suppliers/',
               'template': 'backoffice/pages/suppliers/suppliers.html',
               'legacy': 'suppliers',
               'section': 'purchases'},
 'user_add': {'path': 'users/add/',
              'template': 'backoffice/pages/users/user_add.html',
              'legacy': 'user-form',
              'section': 'users'},
 'users': {'path': 'users/',
           'template': 'backoffice/pages/users/users.html',
           'legacy': 'users',
           'section': 'users'},
 'warehouse_add': {'path': 'warehouses/add/',
                   'template': 'backoffice/pages/warehouses/warehouse_add.html',
                   'legacy': 'warehouse-form',
                   'section': 'inventory'},
 'warehouses': {'path': 'warehouses/',
                'template': 'backoffice/pages/warehouses/warehouses.html',
                'legacy': 'warehouses',
                'section': 'inventory'},
 'warranty_add': {'path': 'warranty/add/',
                  'template': 'backoffice/pages/warranty/warranty_add.html',
                  'legacy': 'warranty-form',
                  'section': 'returns'},
 'warranty': {'path': 'warranty/',
              'template': 'backoffice/pages/warranty/warranty.html',
              'legacy': 'warranty',
              'section': 'returns'}}
