"""Field names used by the reusable table and the client-side CRUD demo."""

COLUMNS = {'products': [['name', 'Product'],
              ['sku', 'SKU'],
              ['category', 'Category'],
              ['brand', 'Brand'],
              ['price', 'Price'],
              ['stock', 'Stock'],
              ['status', 'Status']],
 'orders': [['orderId', 'Order ID'],
            ['customer', 'Customer'],
            ['items', 'Items'],
            ['amount', 'Amount'],
            ['payment', 'Payment'],
            ['status', 'Status'],
            ['date', 'Date']],
 'categories': [['name', 'Category Name'],
                ['slug', 'Slug'],
                ['parent', 'Parent'],
                ['products', 'Products'],
                ['status', 'Status']],
 'brands': [['name', 'Brand Name'],
            ['slug', 'Slug'],
            ['products', 'Products'],
            ['featured', 'Featured'],
            ['status', 'Status']],
 'serials': [['serial', 'Serial / IMEI'],
             ['product', 'Product'],
             ['warehouse', 'Warehouse'],
             ['status', 'Status'],
             ['warrantyEnd', 'Warranty End']],
 'customers': [['name', 'Customer'],
               ['phone', 'Phone'],
               ['email', 'Email'],
               ['orders', 'Orders'],
               ['spent', 'Total Spent'],
               ['group', 'Group'],
               ['status', 'Status']],
 'purchases': [['po', 'PO Number'],
               ['supplier', 'Supplier'],
               ['warehouse', 'Warehouse'],
               ['items', 'Items'],
               ['total', 'Total'],
               ['payment', 'Payment'],
               ['receipt', 'Receipt Status'],
               ['date', 'Date']],
 'suppliers': [['name', 'Supplier'],
               ['phone', 'Phone'],
               ['email', 'Email'],
               ['purchases', 'Purchases'],
               ['outstanding', 'Outstanding'],
               ['terms', 'Payment Terms'],
               ['status', 'Status']],
 'inventory': [['product', 'Product'],
               ['sku', 'SKU'],
               ['warehouse', 'Warehouse'],
               ['available', 'Available'],
               ['reserved', 'Reserved'],
               ['reorder', 'Reorder'],
               ['status', 'Status']],
 'warehouses': [['name', 'Warehouse'],
                ['code', 'Code'],
                ['branch', 'Branch'],
                ['units', 'Stock Units'],
                ['value', 'Stock Value'],
                ['status', 'Status']],
 'expenses': [['expenseNo', 'Expense No'],
              ['date', 'Date'],
              ['category', 'Category'],
              ['description', 'Description'],
              ['method', 'Method'],
              ['amount', 'Amount'],
              ['status', 'Status']],
 'payments': [['transaction', 'Transaction'],
              ['date', 'Date'],
              ['type', 'Type'],
              ['method', 'Method'],
              ['reference', 'Reference'],
              ['amount', 'Amount'],
              ['status', 'Status']],
 'coupons': [['code', 'Code'],
             ['type', 'Type'],
             ['value', 'Value'],
             ['minimum', 'Minimum Purchase'],
             ['usage', 'Usage'],
             ['expiry', 'Expiry'],
             ['status', 'Status']],
 'shipping': [['shipment', 'Shipment'],
              ['order', 'Order'],
              ['customer', 'Customer'],
              ['courier', 'Courier'],
              ['tracking', 'Tracking ID'],
              ['cod', 'COD Amount'],
              ['status', 'Status'],
              ['date', 'Date']],
 'returns': [['returnId', 'Return ID'],
             ['orderId', 'Order ID'],
             ['customer', 'Customer'],
             ['item', 'Item'],
             ['reason', 'Reason'],
             ['refund', 'Refund'],
             ['status', 'Status'],
             ['date', 'Date']],
 'warranty': [['claim', 'Claim No'],
              ['customer', 'Customer'],
              ['product', 'Product'],
              ['serial', 'Serial / IMEI'],
              ['issue', 'Issue'],
              ['resolution', 'Resolution'],
              ['status', 'Status'],
              ['date', 'Date']],
 'users': [['name', 'User'],
           ['email', 'Email'],
           ['role', 'Role'],
           ['branch', 'Branch'],
           ['status', 'Status'],
           ['lastLogin', 'Last Login']],
 'audit': [['date', 'Date & Time'],
           ['user', 'User'],
           ['action', 'Action'],
           ['module', 'Module'],
           ['reference', 'Reference'],
           ['ip', 'IP Address'],
           ['result', 'Result']]}
