from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_catalog_crud_expansion"),
        ("inventory", "0002_import_catalog_opening_stock"),
        ("serial_tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("contact_person", models.CharField(blank=True, max_length=160)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("tax_id", models.CharField(blank=True, max_length=80)),
                ("payment_terms_days", models.PositiveIntegerField(default=0)),
                ("credit_limit", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("opening_balance", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("name", "code")},
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("po_number", models.CharField(max_length=80, unique=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("ordered", "Ordered"), ("partially_received", "Partially Received"), ("received", "Received"), ("cancelled", "Cancelled")], default="draft", max_length=24)),
                ("purchase_date", models.DateField()),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("supplier_invoice_no", models.CharField(blank=True, max_length=100)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("shipping_cost", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("other_cost", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("notes", models.TextField(blank=True)),
                ("actor", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_orders", to="purchasing.supplier")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_orders", to="inventory.warehouse")),
            ],
            options={"ordering": ("-purchase_date", "-id")},
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordered_quantity", models.PositiveIntegerField()),
                ("received_quantity", models.PositiveIntegerField(default=0)),
                ("returned_quantity", models.PositiveIntegerField(default=0)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("purchase", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="purchasing.purchaseorder")),
                ("variant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_items", to="catalog.productvariant")),
            ],
            options={"ordering": ("id",)},
        ),
        migrations.CreateModel(
            name="PurchaseReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("receipt_no", models.CharField(max_length=80, unique=True)),
                ("received_date", models.DateField()),
                ("supplier_challan_no", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
                ("actor", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("purchase", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="receipts", to="purchasing.purchaseorder")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_receipts", to="inventory.warehouse")),
            ],
            options={"ordering": ("-received_date", "-id")},
        ),
        migrations.CreateModel(
            name="PurchaseReceiptItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField()),
                ("serial_data", models.JSONField(blank=True, default=list)),
                ("purchase_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="receipt_items", to="purchasing.purchaseorderitem")),
                ("receipt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="purchasing.purchasereceipt")),
            ],
            options={"ordering": ("id",)},
        ),
        migrations.CreateModel(
            name="PurchasePayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_no", models.CharField(max_length=80, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("method", models.CharField(choices=[("cash", "Cash"), ("bank", "Bank Transfer"), ("bkash", "bKash"), ("nagad", "Nagad"), ("card", "Card"), ("other", "Other")], default="cash", max_length=20)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("payment_date", models.DateField()),
                ("note", models.TextField(blank=True)),
                ("actor", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("purchase", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="purchasing.purchaseorder")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_payments", to="purchasing.supplier")),
            ],
            options={"ordering": ("-payment_date", "-id")},
        ),
        migrations.CreateModel(
            name="PurchaseReturn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("return_no", models.CharField(max_length=80, unique=True)),
                ("return_date", models.DateField()),
                ("reason", models.CharField(max_length=255)),
                ("note", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("posted", "Posted")], default="posted", max_length=20)),
                ("actor", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("purchase", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="returns", to="purchasing.purchaseorder")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_returns", to="purchasing.supplier")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_returns", to="inventory.warehouse")),
            ],
            options={"ordering": ("-return_date", "-id")},
        ),
        migrations.CreateModel(
            name="PurchaseReturnItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                ("purchase_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="return_items", to="purchasing.purchaseorderitem")),
                ("purchase_return", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="purchasing.purchasereturn")),
            ],
            options={"ordering": ("id",)},
        ),
        migrations.CreateModel(
            name="PurchaseReturnSerialUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("return_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="serial_units", to="purchasing.purchasereturnitem")),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_return_links", to="serial_tracking.serializedunit")),
            ],
            options={"ordering": ("id",)},
        ),
        migrations.AddIndex(model_name="supplier", index=models.Index(fields=["is_active", "name"], name="purchase_supplier_active_idx")),
        migrations.AddIndex(model_name="purchaseorder", index=models.Index(fields=["status", "purchase_date"], name="purchase_order_status_idx")),
        migrations.AddIndex(model_name="purchaseorder", index=models.Index(fields=["supplier", "purchase_date"], name="purchase_order_supplier_idx")),
        migrations.AddConstraint(model_name="purchaseorder", constraint=models.CheckConstraint(condition=models.Q(("shipping_cost__gte", 0)), name="purchase_shipping_nonnegative")),
        migrations.AddConstraint(model_name="purchaseorder", constraint=models.CheckConstraint(condition=models.Q(("other_cost__gte", 0)), name="purchase_other_nonnegative")),
        migrations.AddConstraint(model_name="purchaseorder", constraint=models.CheckConstraint(condition=models.Q(("discount_amount__gte", 0)), name="purchase_discount_nonnegative")),
        migrations.AddConstraint(model_name="purchaseorderitem", constraint=models.UniqueConstraint(fields=("purchase", "variant"), name="uniq_purchase_variant")),
        migrations.AddConstraint(model_name="purchaseorderitem", constraint=models.CheckConstraint(condition=models.Q(("ordered_quantity__gt", 0)), name="purchase_ordered_positive")),
        migrations.AddConstraint(model_name="purchaseorderitem", constraint=models.CheckConstraint(condition=models.Q(("received_quantity__gte", 0)), name="purchase_received_nonnegative")),
        migrations.AddConstraint(model_name="purchaseorderitem", constraint=models.CheckConstraint(condition=models.Q(("returned_quantity__gte", 0)), name="purchase_returned_nonnegative")),
        migrations.AddConstraint(model_name="purchaseorderitem", constraint=models.CheckConstraint(condition=models.Q(("unit_cost__gte", 0)), name="purchase_unit_cost_nonnegative")),
        migrations.AddConstraint(model_name="purchaseorderitem", constraint=models.CheckConstraint(condition=models.Q(("discount_amount__gte", 0)), name="purchase_line_discount_nonnegative")),
        migrations.AddConstraint(model_name="purchaseorderitem", constraint=models.CheckConstraint(condition=models.Q(("received_quantity__lte", models.F("ordered_quantity"))), name="purchase_received_not_over_ordered")),
        migrations.AddConstraint(model_name="purchaseorderitem", constraint=models.CheckConstraint(condition=models.Q(("returned_quantity__lte", models.F("received_quantity"))), name="purchase_returned_not_over_received")),
        migrations.AddConstraint(model_name="purchasereceiptitem", constraint=models.UniqueConstraint(fields=("receipt", "purchase_item"), name="uniq_receipt_purchase_item")),
        migrations.AddConstraint(model_name="purchasereceiptitem", constraint=models.CheckConstraint(condition=models.Q(("quantity__gt", 0)), name="purchase_receipt_qty_positive")),
        migrations.AddConstraint(model_name="purchasepayment", constraint=models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="purchase_payment_positive")),
        migrations.AddConstraint(model_name="purchasereturnitem", constraint=models.UniqueConstraint(fields=("purchase_return", "purchase_item"), name="uniq_purchase_return_item")),
        migrations.AddConstraint(model_name="purchasereturnitem", constraint=models.CheckConstraint(condition=models.Q(("quantity__gt", 0)), name="purchase_return_qty_positive")),
        migrations.AddConstraint(model_name="purchasereturnitem", constraint=models.CheckConstraint(condition=models.Q(("unit_cost__gte", 0)), name="purchase_return_cost_nonnegative")),
        migrations.AddConstraint(model_name="purchasereturnserialunit", constraint=models.UniqueConstraint(fields=("return_item", "unit"), name="uniq_purchase_return_serial")),
    ]
