# Generated for TechBari catalog database phase.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="Brand", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120, unique=True)), ("slug", models.SlugField(max_length=140, unique=True)), ("description", models.TextField(blank=True)), ("logo", models.ImageField(blank=True, upload_to="catalog/brands/")), ("static_image_path", models.CharField(blank=True, max_length=255)), ("is_featured", models.BooleanField(default=False)), ("is_active", models.BooleanField(default=True)), ("sort_order", models.PositiveIntegerField(default=0)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True))], options={"ordering": ("sort_order", "name")}),
        migrations.CreateModel(name="Category", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120, unique=True)), ("slug", models.SlugField(max_length=140, unique=True)), ("description", models.TextField(blank=True)), ("image", models.ImageField(blank=True, upload_to="catalog/categories/")), ("static_image_path", models.CharField(blank=True, max_length=255)), ("is_active", models.BooleanField(default=True)), ("sort_order", models.PositiveIntegerField(default=0)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="children", to="catalog.category"))], options={"verbose_name_plural": "categories", "ordering": ("sort_order", "name")}),
        migrations.CreateModel(name="Product", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("public_id", models.SlugField(help_text="Stable browser/cart identifier. Existing demo IDs are preserved.", max_length=80, unique=True)), ("name", models.CharField(max_length=255)), ("slug", models.SlugField(max_length=280, unique=True)), ("short_name", models.CharField(blank=True, max_length=255)), ("subtitle", models.CharField(blank=True, max_length=255)), ("short_description", models.CharField(blank=True, max_length=300)), ("description", models.TextField(blank=True)), ("regular_price", models.DecimalField(decimal_places=2, max_digits=18)), ("sale_price", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)), ("badge", models.CharField(blank=True, max_length=80)), ("badge_class", models.CharField(blank=True, default="blue", max_length=30)), ("detail_badge", models.CharField(blank=True, max_length=80)), ("weight", models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)), ("shipping_class", models.CharField(blank=True, default="standard", max_length=80)), ("warranty", models.CharField(blank=True, max_length=120)), ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("archived", "Archived")], default="active", max_length=20)), ("is_featured", models.BooleanField(default=False)), ("is_new_arrival", models.BooleanField(default=False)), ("meta_title", models.CharField(blank=True, max_length=255)), ("meta_description", models.CharField(blank=True, max_length=500)), ("description_paragraphs", models.JSONField(blank=True, default=list)), ("features", models.JSONField(blank=True, default=list)), ("box_contents", models.JSONField(blank=True, default=list)), ("reviews", models.JSONField(blank=True, default=list)), ("questions", models.JSONField(blank=True, default=list)), ("review_score", models.DecimalField(decimal_places=2, default=0, max_digits=3)), ("review_count", models.PositiveIntegerField(default=0)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("brand", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="products", to="catalog.brand")), ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="products", to="catalog.category"))], options={"ordering": ("-created_at", "name")}),
        migrations.CreateModel(name="ProductImage", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("image", models.ImageField(blank=True, upload_to="catalog/products/%Y/%m/")), ("static_path", models.CharField(blank=True, max_length=255)), ("alt_text", models.CharField(blank=True, max_length=255)), ("role", models.CharField(choices=[("primary", "Primary"), ("gallery", "Gallery"), ("detail", "Detail")], default="gallery", max_length=20)), ("sort_order", models.PositiveIntegerField(default=0)), ("created_at", models.DateTimeField(auto_now_add=True)), ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="catalog.product"))], options={"ordering": ("sort_order", "id")}),
        migrations.CreateModel(name="ProductSpecification", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=160)), ("value", models.CharField(max_length=500)), ("sort_order", models.PositiveIntegerField(default=0)), ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="specifications", to="catalog.product"))], options={"ordering": ("sort_order", "id")}),
        migrations.CreateModel(name="ProductVariant", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(default="Default", max_length=120)), ("sku", models.CharField(max_length=64, unique=True)), ("symbol", models.CharField(blank=True, max_length=16)), ("price_override", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)), ("regular_price_override", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)), ("stock_quantity", models.PositiveIntegerField(default=0)), ("low_stock_alert", models.PositiveIntegerField(default=5)), ("is_default", models.BooleanField(default=False)), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="catalog.product"))], options={"ordering": ("product_id", "-is_default", "id")}),
        migrations.AddIndex(model_name="product", index=models.Index(fields=["status", "created_at"], name="cat_prod_status_created_idx")),
        migrations.AddIndex(model_name="product", index=models.Index(fields=["category", "status"], name="cat_prod_cat_status_idx")),
        migrations.AddIndex(model_name="product", index=models.Index(fields=["brand", "status"], name="cat_prod_brand_status_idx")),
        migrations.AddConstraint(model_name="productspecification", constraint=models.UniqueConstraint(fields=("product", "name"), name="uniq_product_spec_name")),
        migrations.AddConstraint(model_name="productvariant", constraint=models.UniqueConstraint(fields=("product", "name"), name="uniq_product_variant_name")),
    ]
